using Ctrl = Serenity.Demo.BasicSamples.BasicSamplesPage;
using Link = Serenity.Navigation.NavigationLinkAttribute;
using Menu = Serenity.Navigation.NavigationMenuAttribute;

[assembly: Menu(7900, "Basic Samples", icon: "fa-magic")]
[assembly: Menu(7910, "Basic Samples/Dialogs")]
[assembly: Link(7910, "Basic Samples/Dialogs/Chart in a Dialog", typeof(Ctrl), action: nameof(Ctrl.ChartInDialog))]
[assembly: Link(7910, "Basic Samples/Dialogs/Cloneable Entity Dialog", typeof(Ctrl), action: nameof(Ctrl.CloneableEntityDialog))]
[assembly: Link(7910, "Basic Samples/Dialogs/Default Values in New Dialog", typeof(Ctrl), action: nameof(Ctrl.DefaultValuesInNewDialog))]
[assembly: Link(7910, "Basic Samples/Dialogs/Dialog Boxes", typeof(Ctrl), action: nameof(Ctrl.DialogBoxes))]
[assembly: Link(7910, "Basic Samples/Dialogs/Entity Dialog as Panel", typeof(Ctrl), action: nameof(Ctrl.EntityDialogAsPanel), Url = "~/BasicSamples/EntityDialogAsPanel/11077")]
[assembly: Link(7910, "Basic Samples/Dialogs/Get Inserted Record ID", typeof(Ctrl), action: nameof(Ctrl.GetInsertedRecordId))]
[assembly: Link(7910, "Basic Samples/Dialogs/Other Form In Tab", typeof(Ctrl), action: nameof(Ctrl.OtherFormInTab))]
[assembly: Link(7910, "Basic Samples/Dialogs/Other Form, One Toolbar", typeof(Ctrl), action: nameof(Ctrl.OtherFormInTabOneBar))]
[assembly: Link(7910, "Basic Samples/Dialogs/Populate Linked Data", typeof(Ctrl), action: nameof(Ctrl.PopulateLinkedData))]
[assembly: Link(7910, "Basic Samples/Dialogs/Read-Only Dialog", typeof(Ctrl), action: nameof(Ctrl.ReadOnlyDialog))]
[assembly: Link(7910, "Basic Samples/Dialogs/Serial Auto Numbering", typeof(Ctrl), action: nameof(Ctrl.SerialAutoNumber))]
[assembly: Menu(7930, "Basic Samples/Editors")]
[assembly: Link(7930, "Basic Samples/Editors/Changing Lookup Text", typeof(Ctrl), action: nameof(Ctrl.ChangingLookupText))]
[assembly: Link(7930, "Basic Samples/Editors/Filtered Lookup in Detail.", typeof(Ctrl), action: nameof(Ctrl.FilteredLookupInDetailDialog))]
[assembly: Link(7930, "Basic Samples/Editors/Lookup Filter by Multi Val.", typeof(Ctrl), action: nameof(Ctrl.LookupFilterByMultipleValues))]
[assembly: Link(7930, "Basic Samples/Editors/Select with Hardcod.Vals.", typeof(Ctrl), action: nameof(Ctrl.SelectWithHardcodedValues))]
[assembly: Link(7930, "Basic Samples/Editors/Static Text Block", typeof(Ctrl), action: nameof(Ctrl.StaticTextBlock))]
[assembly: Menu(7950, "Basic Samples/Grids")]
[assembly: Link(7950, "Basic Samples/Grids/Custom Links In Grid", typeof(Ctrl), action: nameof(Ctrl.CustomLinksInGrid))]
[assembly: Link(7950, "Basic Samples/Grids/Enabling Row Selection", typeof(Ctrl), action: nameof(Ctrl.EnablingRowSelection))]
[assembly: Link(7950, "Basic Samples/Grids/Grouping and Sum. In Grid", typeof(Ctrl), action: nameof(Ctrl.GroupingAndSummariesInGrid))]
[assembly: Link(7950, "Basic Samples/Grids/Grid Filtered by Criteria", typeof(Ctrl), action: nameof(Ctrl.GridFilteredByCriteria))]
[assembly: Link(7950, "Basic Samples/Grids/Initial Value for Quick Flt.", typeof(Ctrl), action: nameof(Ctrl.InitialValuesForQuickFilters))]
[assembly: Link(7950, "Basic Samples/Grids/Inline Action Buttons", typeof(Ctrl), action: nameof(Ctrl.InlineActionButtons))]
[assembly: Link(7950, "Basic Samples/Grids/Inline Image In Grid", typeof(Ctrl), action: nameof(Ctrl.InlineImageInGrid))]
[assembly: Link(7950, "Basic Samples/Grids/Removing Add Button", typeof(Ctrl), action: nameof(Ctrl.RemovingAddButton))]
[assembly: Link(7950, "Basic Samples/Grids/View Without ID", typeof(Ctrl), action: nameof(Ctrl.ViewWithoutID))]
[assembly: Link(7950, "Basic Samples/Grids/Wrapped Headers", typeof(Ctrl), action: nameof(Ctrl.WrappedHeaders))]