packages:
  - '!**/.*/**'
  - '!**/artifacts/**'
  - 'packages/*'
  - 'common-features'
  - 'common-features/src/*'
  - 'serene/src/Serene.Web'

catalogs:
  serenity:
    "@preact/signals-core": "1.12.1"
    "@vitest/coverage-v8": "3.2.4"
    "chart.js": "4.5.1"
    "dompurify": "3.3.0"
    "dts-bundle-generator": "9.5.1"
    "esbuild": "0.25.11"
    "flatpickr": "4.6.13"
    "glightbox": "3.3.1"
    "glob": "11.0.3"
    "jsdom": "27.0.0"
    "moment": "2.30.1"
    "preact": "10.27.2"
    "typescript": "5.9.3"
    "vitest": "3.2.4"