namespace Serenity.CodeGenerator;

public partial class MvcCommandTests
{

    MvcCommand CreateCommand(string[] viewPaths, out MockFileSystem fileSystem)
    {
        fileSystem = new MockFileSystem();
        var project = new ProjectFileInfo(fileSystem, @"/Repos/MyTest.Web/MyTest.Web.csproj");
        var directory = fileSystem.GetDirectoryName(project.ProjectFile);
        fileSystem.AddFile(project.ProjectFile, "<Project Sdk=\"Microsoft.NET.Sdk.Web\"></Project>");
        fileSystem.AddFile(fileSystem.Combine(directory, "sergen.json"),
            "{\"MVC\": {\"UseRootNamespace\": true}}");
        var command = new MvcCommand(project, new MockGeneratorConsole());
        foreach (var viewPath in viewPaths)
            fileSystem.AddFile(fileSystem.Combine(directory, PathHelper.ToPath(viewPath)), "");
        return command;
    }

    [Fact]
    public void SameSubFolderNameInDifferentParents()
    {
        var expected =
@"// <auto-generated />

namespace MyTest
{
    public static partial class MVC
    {
        /// <summary>Provides paths to view files.</summary>
        public static partial class Views
        {
            /// <summary>Provides view paths in the <c>MyModule</c> folder.</summary>
            public static partial class MyModule
            {
                /// <summary>Provides view paths in the <c>MyModule/A</c> folder.</summary>
                public static partial class A
                {
                    /// <summary>Provides view paths in the <c>MyModule/A/Same</c> folder.</summary>
                    public static partial class Same
                    {
                        /// <summary>The path to the <c>A1</c> view.</summary>
                        public const string A1 = ""~/Modules/MyModule/A/Same/A1.cshtml"";
                        /// <summary>The path to the <c>A2</c> view.</summary>
                        public const string A2 = ""~/Modules/MyModule/A/Same/A2.cshtml"";
                        /// <summary>The path to the <c>A3</c> view.</summary>
                        public const string A3 = ""~/Modules/MyModule/A/Same/A3.cshtml"";
                    }
                }

                /// <summary>Provides view paths in the <c>MyModule/B</c> folder.</summary>
                public static partial class B
                {
                    /// <summary>Provides view paths in the <c>MyModule/B/Same</c> folder.</summary>
                    public static partial class Same
                    {
                        /// <summary>The path to the <c>B1</c> view.</summary>
                        public const string B1 = ""~/Modules/MyModule/B/Same/B1.cshtml"";
                        /// <summary>The path to the <c>B2</c> view.</summary>
                        public const string B2 = ""~/Modules/MyModule/B/Same/B2.cshtml"";
                    }
                }
            }
        }
    }
}".ReplaceLineEndings();

        var command = CreateCommand([
            "Modules/MyModule/A/Same/A1.cshtml",
            "Modules/MyModule/A/Same/A2.cshtml",
            "Modules/MyModule/A/Same/A3.cshtml",
            "Modules/MyModule/B/Same/B1.cshtml",
            "Modules/MyModule/B/Same/B2.cshtml"], out var fileSystem);

        var exitCode = command.Run();
        Assert.Equal(ExitCodes.Success, exitCode);

        var generated = fileSystem.ReadAllText(@"/Repos/MyTest.Web/Imports/MVC/MVC.cs").Trim().ReplaceLineEndings();
        Assert.Equal(expected, generated);
    }
}
