#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serenity.CodeGenerator.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class EntityRepository : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 2 "..\..\Views\EntityRepository.cshtml"
 public dynamic Model { get; set; } 
        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



            
            #line 2 "..\..\Views\EntityRepository.cshtml"
                                                   var dotModule = Model.Module == null ? "" : ("." + Model.Module);

            
            #line default
            #line hidden
WriteLiteral("\r\nnamespace ");


            
            #line 4 "..\..\Views\EntityRepository.cshtml"
      Write(Model.RootNamespace);

            
            #line default
            #line hidden

            
            #line 4 "..\..\Views\EntityRepository.cshtml"
                            Write(dotModule);

            
            #line default
            #line hidden
WriteLiteral(".Repositories\r\n{\r\n    using Serenity;\r\n    using Serenity.Data;\r\n    using Sereni" +
"ty.Services;\r\n    using System;\r\n    using System.Data;\r\n    using MyRow = Entit" +
"ies.");


            
            #line 11 "..\..\Views\EntityRepository.cshtml"
                       Write(Model.RowClassName);

            
            #line default
            #line hidden
WriteLiteral(";\r\n\r\n    public class ");


            
            #line 13 "..\..\Views\EntityRepository.cshtml"
             Write(Model.ClassName);

            
            #line default
            #line hidden
WriteLiteral("Repository\r\n    {\r\n        private static MyRow.RowFields fld { get { return MyRo" +
"w.Fields; } }\r\n\r\n        public CreateResponse Create(IUnitOfWork uow, SaveReque" +
"st<MyRow> request)\r\n        {\r\n            return new MyCreateHandler().Process(" +
"uow, request);\r\n        }\r\n\r\n        public UpdateResponse Update(IUnitOfWork uo" +
"w, SaveRequest<MyRow> request)\r\n        {\r\n            return new MyUpdateHandle" +
"r().Process(uow, request);\r\n        }\r\n\r\n        public DeleteResponse Delete(IU" +
"nitOfWork uow, DeleteRequest request)\r\n        {\r\n            return new MyDelet" +
"eHandler().Process(uow, request);\r\n        }\r\n\r\n        public UndeleteResponse " +
"Undelete(IUnitOfWork uow, UndeleteRequest request)\r\n        {\r\n            retur" +
"n new MyUndeleteHandler().Process(uow, request);\r\n        }\r\n\r\n        public Re" +
"trieveResponse<MyRow> Retrieve(IDbConnection connection, RetrieveRequest request" +
")\r\n        {\r\n            return new MyRetrieveHandler().Process(connection, req" +
"uest);\r\n        }\r\n\r\n        public ListResponse<MyRow> List(IDbConnection conne" +
"ction, ListRequest request)\r\n        {\r\n            return new MyListHandler().P" +
"rocess(connection, request);\r\n        }\r\n\r\n        private class MyCreateHandler" +
" : CreateRequestHandler<MyRow> { }\r\n        private class MyUpdateHandler : Upda" +
"teRequestHandler<MyRow> { }\r\n        private class MyDeleteHandler : DeleteReque" +
"stHandler<MyRow> { }\r\n        private class MyUndeleteHandler : UndeleteRequestH" +
"andler<MyRow> { }\r\n        private class MyRetrieveHandler : RetrieveRequestHand" +
"ler<MyRow> { }\r\n        private class MyListHandler : ListRequestHandler<MyRow> " +
"{ }\r\n    }\r\n}");


        }
    }
}
#pragma warning restore 1591
