using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.Extensions.DependencyInjection;

namespace Serenity.Web;

/// <summary>
/// Authorizes access to a controller action. Optionally checks the permission provided as the first argument.
/// Use special permission key <c>?</c> to check for logged-in users, and <c>*</c> to allow anyone including anonymous access.
/// </summary>
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Method)]
public class PageAuthorizeAttribute : TypeFilterAttribute
{
    /// <summary>
    /// Initializes a new instance of the <see cref="PageAuthorizeAttribute"/> class.
    /// </summary>
    public PageAuthorizeAttribute()
        : base(typeof(PageAuthorizeFilter))
    {
        Arguments = [this];
    }

    private class PageAuthorizeFilter(PageAuthorizeAttribute attr) : IResourceFilter
    {
        readonly PageAuthorizeAttribute attr = attr;

        public void OnResourceExecuted(ResourceExecutedContext context)
        {
        }

        public void OnResourceExecuting(ResourceExecutingContext context)
        {
            if ((string.IsNullOrEmpty(attr.Permission) &&
                 !context.HttpContext.User.IsLoggedIn()) ||
                (!string.IsNullOrEmpty(attr.Permission) &&
                 !context.HttpContext.RequestServices.GetRequiredService<IPermissionService>().HasPermission(attr.Permission)))
            {
                if (context.HttpContext.User.IsLoggedIn())
                    context.Result = new ForbidResult();
                else
                    context.Result = new ChallengeResult();
            }
        }
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="PageAuthorizeAttribute"/> class.
    /// </summary>
    /// <param name="sourceType">The source type.</param>
    /// <param name="attributeTypes">The attribute types.</param>
    /// <exception cref="ArgumentNullException">Source type or attribute types is <c>null</c>.</exception>
    /// <exception cref="ArgumentOutOfRangeException">One of the attribute types
    /// is not a subclass of <see cref="PermissionAttributeBase"/>.</exception>
    protected PageAuthorizeAttribute(Type sourceType, params Type[] attributeTypes)
        : this()
    {
        ArgumentNullException.ThrowIfNull(sourceType);

        if (attributeTypes.IsEmptyOrNull())
            throw new ArgumentNullException(nameof(attributeTypes));

        PermissionAttributeBase attr = null;
        foreach (var attributeType in attributeTypes)
        {
            var lst = sourceType.GetCustomAttributes(attributeType, true);
            if (lst.Length > 0)
            {
                attr = lst[0] as PermissionAttributeBase;
                if (attr == null)
                    throw new ArgumentOutOfRangeException(attributeType.Name +
                        " is not a subclass of PermissionAttributeBase!");

                break;
            }
        }

        if (attr == null)
        {
            throw new ArgumentOutOfRangeException(nameof(sourceType),
                "PageAuthorize attribute is created with source type of " +
                sourceType.Name + ", but it has no " +
                string.Join(" OR ", attributeTypes.Select(x => x.Name)) + " attribute(s)");
        }

        Permission = attr.Permission;
    }

    /// <summary>
    /// Initializes an instance of the <see cref="PageAuthorizeAttribute"/> class, while reading the permission
    /// key from the <see cref="NavigationPermissionAttribute"/> or <see cref="ReadPermissionAttribute"/> of the source type.
    /// </summary>
    /// <param name="sourceType">The source type.</param>
    public PageAuthorizeAttribute(Type sourceType)
        : this(sourceType, typeof(NavigationPermissionAttribute), typeof(ReadPermissionAttribute))
    {
    }

    /// <summary>
    /// Initializes an instance of the <see cref="PageAuthorizeAttribute"/> class with the passed permission key.
    /// </summary>
    /// <param name="permission">The permission key.</param>
    public PageAuthorizeAttribute(object permission)
        : this()
    {
        Permission = permission?.ToString();
    }
    /// <summary>
    /// Initializes an instance of the <see cref="PageAuthorizeAttribute"/> class with a permission key
    /// generated by joining the passed permissions with a colon (<c>:</c>), e.g. <c>module:permission</c>.
    /// </summary>
    /// <param name="module">The module.</param>
    /// <param name="permission">The permission key.</param>
    public PageAuthorizeAttribute(object module, object permission)
        : this(module.ToString() + ":" + permission)
    {
    }

    /// <summary>
    /// Initializes an instance of the <see cref="PageAuthorizeAttribute"/> class with a permission key
    /// generated by joining the passed permissions with a colon (<c>:</c>), e.g. <c>module:submodule:permission</c>.
    /// </summary>
    /// <param name="module">The module.</param>
    /// <param name="submodule">The submodule.</param>
    /// <param name="permission">The permission key.</param>
    public PageAuthorizeAttribute(object module, object submodule, object permission)
        : this(module.ToString() + ":" + submodule + ":" + permission)
    {
    }

    /// <summary>
    /// Gets the permission key.
    /// </summary>
    public string Permission { get; private set; }

    /// <inheritdoc/>
    public override bool Equals(object obj)
    {
        return obj is PageAuthorizeAttribute other &&
            string.Equals(Permission, other.Permission, StringComparison.Ordinal);
    }

    /// <inheritdoc/>
    public override int GetHashCode()
    {
        return base.GetHashCode();
    }
}