namespace Serenity.ComponentModel;

/// <summary>
/// Marks a class so that its accompanying interface is generated by Serenity.Pro.Coder
/// InterfaceSourceGenerator
/// </summary>
/// <seealso cref="Attribute" />
[AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
public class GenerateInterfaceAttribute : Attribute
{
    /// <summary>
    /// Set of features that will be added via RequiresFeature attribute to the interface
    /// </summary>
    public object[]? RequireFeatures { get; set; }

}