namespace Serenity.TypeScript.TsTypes;

public enum DiagnosticMessage
{
#pragma warning disable CS0649
    Unknown = 0,
    Merge_conflict_marker_encountered,
    Digit_expected,
    Unterminated_string_literal,
    Unterminated_template_literal,
    Unexpected_end_of_text,
    Hexadecimal_digit_expected,
    An_extended_Unicode_escape_value_must_be_between_0x0_and_0x10FFFF_inclusive,
    Unterminated_Unicode_escape_sequence,
    Asterisk_Slash_expected,
    Binary_digit_expected,
    Octal_digit_expected,
    Invalid_character,
    Unterminated_regular_expression_literal,
    _0_expected,
    Identifier_expected,
    Declaration_or_statement_expected,
    case_or_default_expected,
    Statement_expected,
    Property_or_signature_expected,
    Unexpected_token_A_constructor_method_accessor_or_property_was_expected,
    Enum_member_expected,
    Expression_expected,
    Variable_declaration_expected,
    Property_destructuring_pattern_expected,
    Array_element_destructuring_pattern_expected,
    Argument_expression_expected,
    Property_assignment_expected,
    Expression_or_comma_expected,
    Parameter_declaration_expected,
    Type_parameter_declaration_expected,
    Type_argument_expected,
    Type_expected,
    Unexpected_token_expected,
    A_type_assertion_expression_is_not_allowed_in_the_left_hand_side_of_an_exponentiation_expression_Consider_enclosing_the_expression_in_parentheses,
    An_unary_expression_with_the_0_operator_is_not_allowed_in_the_left_hand_side_of_an_exponentiation_expression_Consider_enclosing_the_expression_in_parentheses,
    super_must_be_followed_by_an_argument_list_or_member_access,
    Expected_corresponding_JSX_closing_tag_for_0,
    JSX_expressions_must_have_one_parent_element,
    JSX_element_0_has_no_corresponding_closing_tag,
    Declaration_expected,
    or_expected,
    An_AMD_module_cannot_have_multiple_name_assignments,
    Type_argument_list_cannot_be_empty,
    Trailing_comma_not_allowed,
    _0_tag_already_specified,
#pragma warning restore CS0649
}