export interface GridOptions {
    asyncEditorLoading?: boolean;
    asyncEditorLoadDelay?: number;
    asyncPostRenderDelay?: number;
    asyncPostRenderCleanupDelay?: number;
    autoEdit?: boolean;
    autoHeight?: boolean;
    cellFlashingCssClass?: string;
    cellHighlightCssClass?: string;
    dataItemColumnValueExtractor?: () => void;
    groupingPanel?: boolean,
    groupingPanelHeight?: number;
    setGroupingPanelVisibility?: (value: boolean) => void;
    defaultColumnWidth?: number;
    defaultFormatter?: () => void;
    editable?: boolean;
    editCommandHandler?: () => void;
    editorFactory?: () => void;
    editorLock?: any;
    enableAddRow?: boolean;
    enableAsyncPostRender?: boolean;
    enableAsyncPostRenderCleanup?: boolean;
    enableCellRangeSelection?: boolean;
    enableCellNavigation?: boolean;
    enableColumnReorder?: boolean;
    enableRowReordering?: boolean;
    enableTextSelectionOnCells?: boolean;
    explicitInitialization?: boolean;
    forceFitColumns?: boolean;
    forceSyncScrolling?: boolean;
    formatterFactory?: () => void;
    fullWidthRows?: boolean;
    frozenColumn?: number;
    frozenRow?: number;
    frozenBottom?: boolean;
    headerRowHeight?: number;
    leaveSpaceForNewRows?: boolean;
    minBuffer?: number;
    multiColumnSort?: boolean;
    multiSelect?: boolean;
    renderAllCells?: boolean;
    rowHeight?: number;
    selectedCellCssClass?: string;
    showHeaderRow?: boolean;
    showFooterRow?: boolean;
    syncColumnCellResize?: boolean;
    topPanelHeight?: number;
}