namespace Serenity.CodeGeneration;

public partial class EsmEntryPointsGeneratorTests
{
    [Fact]
    public void EmitsComments_AndAutoGeneratedComment_WhenNotOmitted()
    {
        var expected = /*lang=c#*/ """
            // <auto-generated />

            namespace MyTest
            {
                /// <summary>Provides paths to ECMAScript module entry points.</summary>
                public static partial class ESM
                {
                    /// <summary>The module path for the <c>AnotherPage</c> entry point.</summary>
                    public const string AnotherPage = "~/esm/Modules/AnotherPage.js";
                    /// <summary>The module path for the <c>SamplePage</c> entry point.</summary>
                    public const string SamplePage = "~/esm/Modules/Sample/SamplePage.js";
                    /// <summary>The module path for the <c>ScriptInit</c> entry point.</summary>
                    public const string ScriptInit = "~/esm/Modules/Common/ScriptInit.js";
                    /// <summary>The module path for the <c>Sub2Page</c> entry point.</summary>
                    public const string Sub2Page = "~/esm/Modules/Sample/SubPage/Sub2Page.js";
                    /// <summary>The module path for the <c>SubPage</c> entry point.</summary>
                    public const string SubPage = "~/esm/Modules/Sample/SubPage/SubPage.js";
                    /// <summary>The module path for the <c>TestPage</c> entry point.</summary>
                    public const string TestPage = "~/esm/Modules/Admin/TestPage.js";

                    /// <summary>Provides module entry points in the <c>Modules</c> folder.</summary>
                    public static partial class Modules
                    {
                        /// <summary>Provides module entry points in the <c>Modules/Admin</c> folder.</summary>
                        public static partial class Admin
                        {
                            /// <summary>The module path for the <c>TestPage</c> entry point.</summary>
                            public const string TestPage = "~/esm/Modules/Admin/TestPage.js";
                        }

                        /// <summary>The module path for the <c>AnotherPage</c> entry point.</summary>
                        public const string AnotherPage = "~/esm/Modules/AnotherPage.js";

                        /// <summary>Provides module entry points in the <c>Modules/Common</c> folder.</summary>
                        public static partial class Common
                        {
                            /// <summary>The module path for the <c>ScriptInit</c> entry point.</summary>
                            public const string ScriptInit = "~/esm/Modules/Common/ScriptInit.js";
                        }

                        /// <summary>Provides module entry points in the <c>Modules/Sample</c> folder.</summary>
                        public static partial class Sample
                        {
                            /// <summary>The module path for the <c>SamplePage</c> entry point.</summary>
                            public const string SamplePage = "~/esm/Modules/Sample/SamplePage.js";

                            /// <summary>Provides module entry points in the <c>Modules/Sample/SubPage</c> folder.</summary>
                            public static partial class SubPage
                            {
                                /// <summary>The module path for the <c>Sub2Page</c> entry point.</summary>
                                public const string Sub2Page = "~/esm/Modules/Sample/SubPage/Sub2Page.js";
                                /// <summary>The module path for the <c>SubPage_</c> entry point.</summary>
                                public const string SubPage_ = "~/esm/Modules/Sample/SubPage/SubPage.js";
                            }
                        }
                    }
                }
            }
            """.ReplaceLineEndings();

        Assert.Equal(expected, Generate(
            new Options() { OmitComments = false },
            "Modules/Admin/TestPage.ts",
            "Modules/Common/ScriptInit.ts",
            "Modules/Sample/SamplePage.ts",
            "Modules/Sample/SubPage/SubPage.ts",
            "Modules/Sample/SubPage/Sub2Page.ts",
            "Modules/AnotherPage.ts"));
    }
}