// <auto-generated />

namespace Serene.MVC;

/// <summary>Provides paths to ECMAScript module entry points.</summary>
public static partial class ESM
{
    /// <summary>The module path for the <c>LanguagePage</c> entry point.</summary>
    public const string LanguagePage = "~/esm/Modules/Administration/Language/LanguagePage.js";
    /// <summary>The module path for the <c>LoginPage</c> entry point.</summary>
    public const string LoginPage = "~/esm/Modules/Membership/Account/Login/LoginPage.js";
    /// <summary>The module path for the <c>RolePage</c> entry point.</summary>
    public const string RolePage = "~/esm/Modules/Administration/Role/RolePage.js";
    /// <summary>The module path for the <c>ScriptInit</c> entry point.</summary>
    public const string ScriptInit = "~/esm/Modules/Common/ScriptInit.js";
    /// <summary>The module path for the <c>SignUpPage</c> entry point.</summary>
    public const string SignUpPage = "~/esm/Modules/Membership/Account/SignUp/SignUpPage.js";
    /// <summary>The module path for the <c>TranslationPage</c> entry point.</summary>
    public const string TranslationPage = "~/esm/Modules/Administration/Translation/TranslationPage.js";
    /// <summary>The module path for the <c>UserPage</c> entry point.</summary>
    public const string UserPage = "~/esm/Modules/Administration/User/UserPage.js";

    /// <summary>Provides module entry points in the <c>Modules</c> folder.</summary>
    public static partial class Modules
    {
        /// <summary>Provides module entry points in the <c>Modules/Administration</c> folder.</summary>
        public static partial class Administration
        {
            /// <summary>Provides module entry points in the <c>Modules/Administration/Language</c> folder.</summary>
            public static partial class Language
            {
                /// <summary>The module path for the <c>LanguagePage</c> entry point.</summary>
                public const string LanguagePage = "~/esm/Modules/Administration/Language/LanguagePage.js";
            }

            /// <summary>Provides module entry points in the <c>Modules/Administration/Role</c> folder.</summary>
            public static partial class Role
            {
                /// <summary>The module path for the <c>RolePage</c> entry point.</summary>
                public const string RolePage = "~/esm/Modules/Administration/Role/RolePage.js";
            }

            /// <summary>Provides module entry points in the <c>Modules/Administration/Translation</c> folder.</summary>
            public static partial class Translation
            {
                /// <summary>The module path for the <c>TranslationPage</c> entry point.</summary>
                public const string TranslationPage = "~/esm/Modules/Administration/Translation/TranslationPage.js";
            }

            /// <summary>Provides module entry points in the <c>Modules/Administration/User</c> folder.</summary>
            public static partial class User
            {
                /// <summary>The module path for the <c>UserPage</c> entry point.</summary>
                public const string UserPage = "~/esm/Modules/Administration/User/UserPage.js";
            }
        }

        /// <summary>Provides module entry points in the <c>Modules/Common</c> folder.</summary>
        public static partial class Common
        {
            /// <summary>The module path for the <c>ScriptInit</c> entry point.</summary>
            public const string ScriptInit = "~/esm/Modules/Common/ScriptInit.js";
        }

        /// <summary>Provides module entry points in the <c>Modules/Membership</c> folder.</summary>
        public static partial class Membership
        {
            /// <summary>Provides module entry points in the <c>Modules/Membership/Account</c> folder.</summary>
            public static partial class Account
            {
                /// <summary>Provides module entry points in the <c>Modules/Membership/Account/Login</c> folder.</summary>
                public static partial class Login
                {
                    /// <summary>The module path for the <c>LoginPage</c> entry point.</summary>
                    public const string LoginPage = "~/esm/Modules/Membership/Account/Login/LoginPage.js";
                }

                /// <summary>Provides module entry points in the <c>Modules/Membership/Account/SignUp</c> folder.</summary>
                public static partial class SignUp
                {
                    /// <summary>The module path for the <c>SignUpPage</c> entry point.</summary>
                    public const string SignUpPage = "~/esm/Modules/Membership/Account/SignUp/SignUpPage.js";
                }
            }
        }
    }
}