// <auto-generated />

namespace Serene.MVC;

/// <summary>Provides paths to view files.</summary>
public static partial class Views
{
    /// <summary>Provides view paths in the <c>Common</c> folder.</summary>
    public static partial class Common
    {
        /// <summary>Provides view paths in the <c>Common/Dashboard</c> folder.</summary>
        public static partial class Dashboard
        {
            /// <summary>The path to the <c>DashboardIndex</c> view.</summary>
            public const string DashboardIndex = "~/Modules/Common/Dashboard/DashboardIndex.cshtml";
        }
    }

    /// <summary>Provides view paths in the <c>Errors</c> folder.</summary>
    public static partial class Errors
    {
        /// <summary>The path to the <c>AccessDenied</c> view.</summary>
        public const string AccessDenied = "~/Views/Errors/AccessDenied.cshtml";
        /// <summary>The path to the <c>ValidationError</c> view.</summary>
        public const string ValidationError = "~/Views/Errors/ValidationError.cshtml";
    }

    /// <summary>Provides view paths in the <c>Membership</c> folder.</summary>
    public static partial class Membership
    {
        /// <summary>Provides view paths in the <c>Membership/Account</c> folder.</summary>
        public static partial class Account
        {
            /// <summary>Provides view paths in the <c>Membership/Account/Login</c> folder.</summary>
            public static partial class Login
            {
                /// <summary>The path to the <c>LoginPage</c> view.</summary>
                public const string LoginPage = "~/Modules/Membership/Account/Login/LoginPage.cshtml";
            }

            /// <summary>Provides view paths in the <c>Membership/Account/SignUp</c> folder.</summary>
            public static partial class SignUp
            {
                /// <summary>The path to the <c>ActivateEmail</c> view.</summary>
                public const string ActivateEmail = "~/Modules/Membership/Account/SignUp/ActivateEmail.cshtml";
                /// <summary>The path to the <c>SignUpPage</c> view.</summary>
                public const string SignUpPage = "~/Modules/Membership/Account/SignUp/SignUpPage.cshtml";
            }
        }
    }

    /// <summary>Provides view paths in the <c>Shared</c> folder.</summary>
    public static partial class Shared
    {
        /// <summary>The path to the <c>_Layout</c> view.</summary>
        public const string _Layout = "~/Views/Shared/_Layout.cshtml";
        /// <summary>The path to the <c>_LayoutHead</c> view.</summary>
        public const string _LayoutHead = "~/Views/Shared/_LayoutHead.cshtml";
        /// <summary>The path to the <c>_LayoutNoNavigation</c> view.</summary>
        public const string _LayoutNoNavigation = "~/Views/Shared/_LayoutNoNavigation.cshtml";
        /// <summary>The path to the <c>_Sidebar</c> view.</summary>
        public const string _Sidebar = "~/Views/Shared/_Sidebar.cshtml";
        /// <summary>The path to the <c>Error</c> view.</summary>
        public const string Error = "~/Views/Shared/Error.cshtml";
    }
}