name: Bug report
description: Create a bug report to help us improve Serenity Platform
title: "[Bug report]: <Short description of the bug>"
labels: waiting-for-check
assignees: VictorTomaili

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: confirmation
    attributes:
      label: Before submitting the bug report, please read and check the following items
      description: We need to make sure this is not a false positive bug report.
      options:
        - label: This isn't a feature request or a discussion topic (Please use discussions for that)
          required: true
        - label: I have searched open and closed issues for duplicates
          required: true
        - label: I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
          required: true
        - label: I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
          required: true
        - label: I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen (included images if possible)?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: what-did-you-expect
    attributes:
      label: What did you expect to happen?
      description: A clear and concise description of what you expected to happen.
      placeholder: Expectations!
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce?
      description: Also tell us, how we can reproduce.
      placeholder: Tell us how we can reproduce!
    validations:
      required: true
  - type: input
    id: serenity-versions
    attributes:
      label: What Serenity Nuget Versions are you seeing the problem on? (separated by comma)
      placeholder: Serenity.Scripts 1.0.0
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        # Development environment details
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output.
      render: console
  - type: input
    id: template-version
    attributes:
      label: Serene template version
      description: What version of the Serene Template do you use?
      placeholder: "1.0.0"
  - type: input
    id: sergen-version
    attributes:
      label: Sergen version
      description: What version of the Sergen do you use?
      placeholder: "1.0.0"
  - type: input
    id: code-editor
    attributes:
      label: Code editor
      description: What code editor are you using? And which version?
      placeholder: "Visual Studio 2022, version 1.0.0"
  - type: input
    id: operating-system
    attributes:
      label: Operating System
      description: What is your operating system?
      placeholder: "Windows 11"
  - type: input
    id: nodejs-version
    attributes:
      label: Node.js version
      description: What is your Node.js version?
      placeholder: "v1.0.0"
  - type: input
    id: typescript-version
    attributes:
      label: TypeScript version
      description: What is the current version of TypeScript?
      placeholder: "1.0.0"
  - type: input
    id: database-type
    attributes:
      label: Database type and version
      description: What database do you use, and what is the version of it?
      placeholder: "SQL Server, version 1.0.0"
  - type: markdown
    attributes:
      value: |
        # Client details
  - type: input
    id: device
    attributes:
      label: On which device do you see the problem?
      placeholder: "Desktop, Laptop, Tablet, Phone, etc."
  - type: input
    id: device-os
    attributes:
      label: On which operating system do you see the problem?
      placeholder: "Windows, Mac, Linux, IOS, Android, etc."
  - type: dropdown
    id: browsers
    attributes:
      label: On which browsers do you see the problem?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
  - type: input
    id: browser-version
    attributes:
      label: On what version of the browsers do you see the problem?
      placeholder: "The version number of the browser"
  - type: markdown
    attributes:
      value: |
        # Extra details
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Additional information that may help us with the bug report.
      placeholder: "Additional information"
