// <auto-generated />

namespace Serenity.Extensions.MVC;

/// <summary>Provides paths to view files.</summary>
public static partial class Views
{
    /// <summary>Provides view paths in the <c>Membership</c> folder.</summary>
    public static partial class Membership
    {
        /// <summary>Provides view paths in the <c>Membership/PasswordActions</c> folder.</summary>
        public static partial class PasswordActions
        {
            /// <summary>The path to the <c>ResetPasswordEmail</c> view.</summary>
            public const string ResetPasswordEmail = "~/Areas/Serenity.Extensions/Membership/PasswordActions/ResetPasswordEmail.cshtml";
        }
    }

    /// <summary>Provides view paths in the <c>ModulePage</c> folder.</summary>
    public static partial class ModulePage
    {
        /// <summary>The path to the <c>ModulePage</c> view.</summary>
        public const string ModulePage_ = "~/Areas/Serenity.Extensions/ModulePage/ModulePage.cshtml";
    }

    /// <summary>Provides view paths in the <c>Reporting</c> folder.</summary>
    public static partial class Reporting
    {
        /// <summary>The path to the <c>ReportPage</c> view.</summary>
        public const string ReportPage = "~/Areas/Serenity.Extensions/Reporting/ReportPage.cshtml";
    }
}