namespace Serenity.CodeGeneration;

public partial class ClientTypesGeneratorTests
{
    [Fact]
    public void Skips_Declaration_Types()
    {
        var files = Generate(null, true, ("Modules/TestEditor.d.ts", /*lang=typescript*/ """
            import { Decorators, Widget } from "@serenity-is/corelib"

            @Decorators.registerEditor('MyProject.MyTest.TestEditor')
            export class TestEditor extends Widget {
            }
            """));

        Assert.Empty(files);
    }

    [Fact]
    public void Skips_Non_Local_Node_Modules_Types()
    {
        var files = Generate(null, true,
            ("Modules/App.ts", /*lang=typescript*/ """
                import { PkgEditor } from "some-pkg";
                export const x = PkgEditor;
                """),
            ("node_modules/some-pkg/package.json", /*lang=json*/ """
                {
                    "name": "some-pkg",
                    "types": "index.ts"
                }
                """),
            ("node_modules/some-pkg/index.ts", /*lang=typescript*/ """
                import { Decorators, Widget } from "@serenity-is/corelib"

                @Decorators.registerEditor('Some.Package.Editor')
                export class PkgEditor extends Widget {
                }
                """));

        Assert.Empty(files);
    }

    [Fact]
    public void Generates_Comments_When_Not_Omitted()
    {
        var files = Generate(null, false, ("Modules/TestEditor.ts", /*lang=typescript*/ """
            import { Decorators, Widget } from "@serenity-is/corelib"

            @Decorators.registerEditor('MyProject.MyTest.TestEditor')
            export class TestEditor extends Widget {
            }
            """));

        var text = Read(files, "MyTest.TestEditorAttribute.cs");
        Assert.StartsWith("// <auto-generated />", text);
        Assert.Contains("/// <summary>An attribute that sets the editor type to <c>MyProject.MyTest.TestEditor</c> and its options.</summary>", text);
    }

    [Fact]
    public void Uses_File_Scoped_Namespaces()
    {
        var files = Generate(null, true, true, ("Modules/TestOptions.ts", /*lang=typescript*/ """
            import { TransformInclude } from "@serenity-is/corelib"

            export interface TestOptions extends TransformInclude {
                token?: string;
            }
            """));

        var text = Read(files, "TestOptions.generated.cs");
        Assert.Equal("""
            namespace MyProject;

            public partial class TestOptions
            {
                public string token { get; set; }
            }
            """.ReplaceLineEndings(), text);
    }
}
