#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serenity.CodeGenerator.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class EntityPageController : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 2 "..\..\Views\EntityPageController.cshtml"
 public dynamic Model { get; set; } 
        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



            
            #line 2 "..\..\Views\EntityPageController.cshtml"
                                                   
    var dotModule = Model.Module == null ? "" : ("." + Model.Module);
    var modulePath = Model.Module ?? Model.RootNamespace;
    var modulePrefix = (Model.Module == null ? "" : (Model.Module + "/"));


            
            #line default
            #line hidden
WriteLiteral("\r\n[assembly:Serenity.Navigation.NavigationLink(int.MaxValue, \"");


            
            #line 8 "..\..\Views\EntityPageController.cshtml"
                                                        Write(modulePrefix);

            
            #line default
            #line hidden

            
            #line 8 "..\..\Views\EntityPageController.cshtml"
                                                                       Write(Model.ClassName);

            
            #line default
            #line hidden
WriteLiteral("\", typeof(");


            
            #line 8 "..\..\Views\EntityPageController.cshtml"
                                                                                                   Write(Model.RootNamespace);

            
            #line default
            #line hidden

            
            #line 8 "..\..\Views\EntityPageController.cshtml"
                                                                                                                         Write(dotModule);

            
            #line default
            #line hidden
WriteLiteral(".Pages.");


            
            #line 8 "..\..\Views\EntityPageController.cshtml"
                                                                                                                                            Write(Model.ClassName);

            
            #line default
            #line hidden
WriteLiteral("Controller))]\r\n\r\nnamespace ");


            
            #line 10 "..\..\Views\EntityPageController.cshtml"
      Write(Model.RootNamespace);

            
            #line default
            #line hidden

            
            #line 10 "..\..\Views\EntityPageController.cshtml"
                            Write(dotModule);

            
            #line default
            #line hidden
WriteLiteral(".Pages\r\n{\r\n    using Serenity;\r\n    using Serenity.Web;\r\n    using System.Web.Mvc" +
";\r\n\r\n    [RoutePrefix(\"");


            
            #line 16 "..\..\Views\EntityPageController.cshtml"
              Write(modulePrefix);

            
            #line default
            #line hidden

            
            #line 16 "..\..\Views\EntityPageController.cshtml"
                             Write(Model.ClassName);

            
            #line default
            #line hidden
WriteLiteral("\"), Route(\"{action=index}\")]\r\n    public class ");


            
            #line 17 "..\..\Views\EntityPageController.cshtml"
             Write(Model.ClassName);

            
            #line default
            #line hidden
WriteLiteral("Controller : Controller\r\n    {\r\n        [PageAuthorize(\"");


            
            #line 19 "..\..\Views\EntityPageController.cshtml"
                    Write(Model.Permission);

            
            #line default
            #line hidden
WriteLiteral("\")]\r\n        public ActionResult Index()\r\n        {\r\n            return View(\"~/M" +
"odules/");


            
            #line 22 "..\..\Views\EntityPageController.cshtml"
                               Write(modulePath);

            
            #line default
            #line hidden
WriteLiteral("/");


            
            #line 22 "..\..\Views\EntityPageController.cshtml"
                                             Write(Model.ClassName);

            
            #line default
            #line hidden
WriteLiteral("/");


            
            #line 22 "..\..\Views\EntityPageController.cshtml"
                                                                Write(Model.ClassName);

            
            #line default
            #line hidden
WriteLiteral("Index.cshtml\");\r\n        }\r\n    }\r\n}");


        }
    }
}
#pragma warning restore 1591
