#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serenity.CodeGenerator.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class EntityCss : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden
 public dynamic Model { get; set; } 
        public override void Execute()
        {


WriteLiteral(Environment.NewLine);



                                                   
    var moduleDash = Model.Module == null ? "" : (Model.Module + "-");


WriteLiteral(Environment.NewLine + ".s-");


Write(moduleDash);


            Write(Model.ClassName);

WriteLiteral("Dialog {" + Environment.NewLine + "    > .size { width: 650px; }" + Environment.NewLine + "    .caption { width: 150px; }" + Environment.NewLine + "}");


        }
    }
}
#pragma warning restore 1591
