#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serenity.CodeGenerator.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class EntityScriptDialog : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 2 "..\..\Views\EntityScriptDialog.cshtml"
 public dynamic Model { get; set; } 
        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



            
            #line 2 "..\..\Views\EntityScriptDialog.cshtml"
                                                   
    var dotModule = Model.Module == null ? "" : ("." + Model.Module);
    var moduleDot = Model.Module == null ? "" : (Model.Module + ".");
    var moduleSlash = Model.Module == null ? "" : (Model.Module + "/");


            
            #line default
            #line hidden
WriteLiteral("namespace ");


            
            #line 7 "..\..\Views\EntityScriptDialog.cshtml"
      Write(Model.RootNamespace);

            
            #line default
            #line hidden

            
            #line 7 "..\..\Views\EntityScriptDialog.cshtml"
                            Write(dotModule);

            
            #line default
            #line hidden
WriteLiteral("\r\n{\r\n    using jQueryApi;\r\n    using Serenity;\r\n    using System.Collections.Gene" +
"ric;\r\n\r\n    [IdProperty(\"");


            
            #line 13 "..\..\Views\EntityScriptDialog.cshtml"
            Write(Model.Identity);

            
            #line default
            #line hidden

            
            #line 13 "..\..\Views\EntityScriptDialog.cshtml"
                                WriteLiteral("\")");

            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\EntityScriptDialog.cshtml"
                                   if (Model.NameField != null) {
            
            #line default
            #line hidden
WriteLiteral(", NameProperty(\"");


            
            #line 13 "..\..\Views\EntityScriptDialog.cshtml"
                                                                                  Write(Model.NameField);

            
            #line default
            #line hidden
WriteLiteral("\")");


            
            #line 13 "..\..\Views\EntityScriptDialog.cshtml"
                                                                                                                }
            
            #line default
            #line hidden

            
            #line 13 "..\..\Views\EntityScriptDialog.cshtml"
                                                                                                                  if (Model.IsActiveField != null) {
            
            #line default
            #line hidden
WriteLiteral(", IsActiveProperty(\"");


            
            #line 13 "..\..\Views\EntityScriptDialog.cshtml"
                                                                                                                                                                          Write(Model.IsActiveField);

            
            #line default
            #line hidden
WriteLiteral("\")");


            
            #line 13 "..\..\Views\EntityScriptDialog.cshtml"
                                                                                                                                                                                                             }
            
            #line default
            #line hidden
WriteLiteral("]\r\n    [FormKey(\"");


            
            #line 14 "..\..\Views\EntityScriptDialog.cshtml"
          Write(moduleDot);

            
            #line default
            #line hidden

            
            #line 14 "..\..\Views\EntityScriptDialog.cshtml"
                      Write(Model.ClassName);

            
            #line default
            #line hidden
WriteLiteral("\"), LocalTextPrefix(\"");


            
            #line 14 "..\..\Views\EntityScriptDialog.cshtml"
                                                             Write(moduleDot);

            
            #line default
            #line hidden

            
            #line 14 "..\..\Views\EntityScriptDialog.cshtml"
                                                                         Write(Model.ClassName);

            
            #line default
            #line hidden
WriteLiteral("\"), Service(\"");


            
            #line 14 "..\..\Views\EntityScriptDialog.cshtml"
                                                                                                        Write(moduleSlash);

            
            #line default
            #line hidden

            
            #line 14 "..\..\Views\EntityScriptDialog.cshtml"
                                                                                                                      Write(Model.ClassName);

            
            #line default
            #line hidden
WriteLiteral("\")]\r\n    public class ");


            
            #line 15 "..\..\Views\EntityScriptDialog.cshtml"
             Write(Model.ClassName);

            
            #line default
            #line hidden
WriteLiteral("Dialog : EntityDialog<");


            
            #line 15 "..\..\Views\EntityScriptDialog.cshtml"
                                                     Write(Model.RowClassName);

            
            #line default
            #line hidden
WriteLiteral(">\r\n    {\r\n    }\r\n}");


        }
    }
}
#pragma warning restore 1591
