#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serenity.CodeGenerator.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class EntityEndpoint : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 2 "..\..\Views\EntityEndpoint.cshtml"
 public dynamic Model { get; set; } 
        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



            
            #line 2 "..\..\Views\EntityEndpoint.cshtml"
                                                   var dotModule = Model.Module == null ? "" : ("." + Model.Module); var modulePrefix = (Model.Module == null ? "" : (Model.Module + "/"));

            
            #line default
            #line hidden
WriteLiteral("\r\nnamespace ");


            
            #line 4 "..\..\Views\EntityEndpoint.cshtml"
      Write(Model.RootNamespace);

            
            #line default
            #line hidden

            
            #line 4 "..\..\Views\EntityEndpoint.cshtml"
                            Write(dotModule);

            
            #line default
            #line hidden
WriteLiteral(".Endpoints\r\n{\r\n    using Serenity;\r\n    using Serenity.Services;\r\n    using Syste" +
"m.Web.Mvc;\r\n    using MyRepository = Repositories.");


            
            #line 9 "..\..\Views\EntityEndpoint.cshtml"
                                  Write(Model.ClassName);

            
            #line default
            #line hidden
WriteLiteral("Repository;\r\n    using MyRow = Entities.");


            
            #line 10 "..\..\Views\EntityEndpoint.cshtml"
                       Write(Model.RowClassName);

            
            #line default
            #line hidden
WriteLiteral(";\r\n\r\n    [ServiceAuthorize]\r\n    [RoutePrefix(\"Services/");


            
            #line 13 "..\..\Views\EntityEndpoint.cshtml"
                       Write(modulePrefix);

            
            #line default
            #line hidden

            
            #line 13 "..\..\Views\EntityEndpoint.cshtml"
                                      Write(Model.ClassName);

            
            #line default
            #line hidden
WriteLiteral("\"), Route(\"{action}\")]\r\n    public class ");


            
            #line 14 "..\..\Views\EntityEndpoint.cshtml"
             Write(Model.ClassName);

            
            #line default
            #line hidden
WriteLiteral("Controller : Controller\r\n    {\r\n        [AcceptVerbs(\"POST\"), JsonFilter]\r\n      " +
"  public Result<SaveResponse> Create(SaveRequest<MyRow> request)\r\n        {\r\n   " +
"         return this.InTransaction(\"");


            
            #line 19 "..\..\Views\EntityEndpoint.cshtml"
                                   Write(Model.Schema);

            
            #line default
            #line hidden
WriteLiteral("\", (uow) => new MyRepository().Create(uow, request));\r\n        }\r\n\r\n        [Acce" +
"ptVerbs(\"POST\"), JsonFilter]\r\n        public Result<SaveResponse> Update(SaveReq" +
"uest<MyRow> request)\r\n        {\r\n            return this.InTransaction(\"");


            
            #line 25 "..\..\Views\EntityEndpoint.cshtml"
                                   Write(Model.Schema);

            
            #line default
            #line hidden
WriteLiteral("\", (uow) => new MyRepository().Update(uow, request));\r\n        }\r\n \r\n        [Acc" +
"eptVerbs(\"POST\"), JsonFilter]\r\n        public Result<DeleteResponse> Delete(Dele" +
"teRequest request)\r\n        {\r\n            return this.InTransaction(\"");


            
            #line 31 "..\..\Views\EntityEndpoint.cshtml"
                                   Write(Model.Schema);

            
            #line default
            #line hidden
WriteLiteral("\", (uow) => new MyRepository().Delete(uow, request));\r\n        }\r\n\r\n        [Acce" +
"ptVerbs(\"POST\"), JsonFilter]\r\n        public Result<UndeleteResponse> Undelete(U" +
"ndeleteRequest request)\r\n        {\r\n            return this.InTransaction(\"");


            
            #line 37 "..\..\Views\EntityEndpoint.cshtml"
                                   Write(Model.Schema);

            
            #line default
            #line hidden
WriteLiteral("\", (uow) => new MyRepository().Undelete(uow, request));\r\n        }\r\n\r\n        [Ac" +
"ceptVerbs(\"GET\", \"POST\"), JsonFilter]\r\n        public Result<RetrieveResponse<My" +
"Row>> Retrieve(RetrieveRequest request)\r\n        {\r\n            return this.UseC" +
"onnection(\"");


            
            #line 43 "..\..\Views\EntityEndpoint.cshtml"
                                   Write(Model.Schema);

            
            #line default
            #line hidden
WriteLiteral("\", (cnn) => new MyRepository().Retrieve(cnn, request));\r\n        }\r\n\r\n        [Ac" +
"ceptVerbs(\"GET\", \"POST\"), JsonFilter]\r\n        public Result<ListResponse<MyRow>" +
"> List(ListRequest request)\r\n        {\r\n            return this.UseConnection(\"");


            
            #line 49 "..\..\Views\EntityEndpoint.cshtml"
                                   Write(Model.Schema);

            
            #line default
            #line hidden
WriteLiteral("\", (cnn) => new MyRepository().List(cnn, request));\r\n        }\r\n    }\r\n}\r\n");


        }
    }
}
#pragma warning restore 1591
