#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serenity.CodeGenerator.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class EntityPageIndex : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 2 "..\..\Views\EntityPageIndex.cshtml"
 public dynamic Model { get; set; } 
        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



            
            #line 2 "..\..\Views\EntityPageIndex.cshtml"
                                                   var dotModule = Model.Module == null ? "" : ("." + Model.Module);

            
            #line default
            #line hidden

WriteLiteral("@{\r\n    ViewBag.Title = Serenity.LocalText.Get(\"Db");


            
            #line 4 "..\..\Views\EntityPageIndex.cshtml"
                                          Write(dotModule);

            
            #line default
            #line hidden
WriteLiteral(".");


            
            #line 4 "..\..\Views\EntityPageIndex.cshtml"
                                                       Write(Model.ClassName);

            
            #line default
            #line hidden
WriteLiteral(".EntityPlural\");\r\n}\r\n\r\n<div id=\"GridDiv\"></div>\r\n\r\n<script type=\"text/javascript\"" +
">\r\n    jQuery(function () {\r\n        new ");


            
            #line 11 "..\..\Views\EntityPageIndex.cshtml"
        Write(Model.RootNamespace);

            
            #line default
            #line hidden

            
            #line 11 "..\..\Views\EntityPageIndex.cshtml"
                              Write(dotModule);

            
            #line default
            #line hidden
WriteLiteral(".");


            
            #line 11 "..\..\Views\EntityPageIndex.cshtml"
                                           Write(Model.ClassName);

            
            #line default
            #line hidden
WriteLiteral("Grid($(\'#GridDiv\'), {\r\n        });\r\n\r\n        Q.initFullHeightGridPage($(\'#GridDi" +
"v\'));\r\n    });\r\n</script>");


        }
    }
}
#pragma warning restore 1591
