#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serenity.CodeGenerator.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class EntityEndpoint : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 2 "..\..\Views\EntityEndpoint.cshtml"
 public dynamic Model { get; set; } 
        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



            
            #line 2 "..\..\Views\EntityEndpoint.cshtml"
                                                   var dotModule = Model.Module == null ? "" : ("." + Model.Module); var modulePrefix = (Model.Module == null ? "" : (Model.Module + "/"));


            
            #line default
            #line hidden
WriteLiteral("namespace ");


            
            #line 4 "..\..\Views\EntityEndpoint.cshtml"
      Write(Model.RootNamespace);

            
            #line default
            #line hidden

            
            #line 4 "..\..\Views\EntityEndpoint.cshtml"
                            Write(dotModule);

            
            #line default
            #line hidden
WriteLiteral(".Endpoints\r\n{\r\n    using Serenity;\r\n    using Serenity.Data;\r\n    using Serenity." +
"Services;\r\n    using System.Data;\r\n    using System.Web.Mvc;\r\n    using MyReposi" +
"tory = Repositories.");


            
            #line 11 "..\..\Views\EntityEndpoint.cshtml"
                                  Write(Model.ClassName);

            
            #line default
            #line hidden
WriteLiteral("Repository;\r\n    using MyRow = Entities.");


            
            #line 12 "..\..\Views\EntityEndpoint.cshtml"
                       Write(Model.RowClassName);

            
            #line default
            #line hidden
WriteLiteral(";\r\n\r\n    [RoutePrefix(\"Services/");


            
            #line 14 "..\..\Views\EntityEndpoint.cshtml"
                       Write(modulePrefix);

            
            #line default
            #line hidden

            
            #line 14 "..\..\Views\EntityEndpoint.cshtml"
                                      Write(Model.ClassName);

            
            #line default
            #line hidden
WriteLiteral("\"), Route(\"{action}\")]\r\n    [ConnectionKey(\"");


            
            #line 15 "..\..\Views\EntityEndpoint.cshtml"
               Write(Model.ConnectionKey);

            
            #line default
            #line hidden
WriteLiteral("\"), ServiceAuthorize(\"");


            
            #line 15 "..\..\Views\EntityEndpoint.cshtml"
                                                          Write(Model.Permission);

            
            #line default
            #line hidden
WriteLiteral("\")]\r\n    public class ");


            
            #line 16 "..\..\Views\EntityEndpoint.cshtml"
             Write(Model.ClassName);

            
            #line default
            #line hidden
WriteLiteral(@"Controller : ServiceEndpoint
    {
        [HttpPost]
        public SaveResponse Create(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            return new MyRepository().Create(uow, request);
        }

        [HttpPost]
        public SaveResponse Update(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            return new MyRepository().Update(uow, request);
        }
 
        [HttpPost]
        public DeleteResponse Delete(IUnitOfWork uow, DeleteRequest request)
        {
            return new MyRepository().Delete(uow, request);
        }

");


            
            #line 36 "..\..\Views\EntityEndpoint.cshtml"
 if (Model.IsActiveField != null) {

            
            #line default
            #line hidden
WriteLiteral("        [HttpPost]\r\n        public UndeleteResponse Undelete(IUnitOfWork uow, Und" +
"eleteRequest request)\r\n        {\r\n            return new MyRepository().Undelete" +
"(uow, request);\r\n        }\r\n");

WriteLiteral("\r\n");


            
            #line 43 "..\..\Views\EntityEndpoint.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral(@"        public RetrieveResponse<MyRow> Retrieve(IDbConnection connection, RetrieveRequest request)
        {
            return new MyRepository().Retrieve(connection, request);
        }

        public ListResponse<MyRow> List(IDbConnection connection, ListRequest request)
        {
            return new MyRepository().List(connection, request);
        }
    }
}
");


        }
    }
}
#pragma warning restore 1591
