#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serenity.CodeGenerator.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class EntityRepository : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 2 "..\..\Views\EntityRepository.cshtml"
 public dynamic Model { get; set; } 
        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



            
            #line 2 "..\..\Views\EntityRepository.cshtml"
                                                   var dotModule = Model.Module == null ? "" : ("." + Model.Module);

            
            #line default
            #line hidden
WriteLiteral("\r\nnamespace ");


            
            #line 4 "..\..\Views\EntityRepository.cshtml"
      Write(Model.RootNamespace);

            
            #line default
            #line hidden

            
            #line 4 "..\..\Views\EntityRepository.cshtml"
                            Write(dotModule);

            
            #line default
            #line hidden
WriteLiteral(".Repositories\r\n{\r\n    using Serenity;\r\n    using Serenity.Data;\r\n    using Sereni" +
"ty.Services;\r\n    using System;\r\n    using System.Data;\r\n    using MyRow = Entit" +
"ies.");


            
            #line 11 "..\..\Views\EntityRepository.cshtml"
                       Write(Model.RowClassName);

            
            #line default
            #line hidden
WriteLiteral(";\r\n\r\n    public class ");


            
            #line 13 "..\..\Views\EntityRepository.cshtml"
             Write(Model.ClassName);

            
            #line default
            #line hidden
WriteLiteral(@"Repository
    {
        private static MyRow.RowFields fld { get { return MyRow.Fields; } }

        public SaveResponse Create(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            return new MySaveHandler().Process(uow, request, SaveRequestType.Create);
        }

        public SaveResponse Update(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            return new MySaveHandler().Process(uow, request, SaveRequestType.Update);
        }

        public DeleteResponse Delete(IUnitOfWork uow, DeleteRequest request)
        {
            return new MyDeleteHandler().Process(uow, request);
        }

");


            
            #line 32 "..\..\Views\EntityRepository.cshtml"
 if (Model.IsActiveField != null) {

            
            #line default
            #line hidden
WriteLiteral("        public UndeleteResponse Undelete(IUnitOfWork uow, UndeleteRequest request" +
")\r\n        {\r\n            return new MyUndeleteHandler().Process(uow, request);\r" +
"\n        }\r\n");

WriteLiteral("\r\n");


            
            #line 38 "..\..\Views\EntityRepository.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral(@"        public RetrieveResponse<MyRow> Retrieve(IDbConnection connection, RetrieveRequest request)
        {
            return new MyRetrieveHandler().Process(connection, request);
        }

        public ListResponse<MyRow> List(IDbConnection connection, ListRequest request)
        {
            return new MyListHandler().Process(connection, request);
        }

        private class MySaveHandler : SaveRequestHandler<MyRow> { }
        private class MyDeleteHandler : DeleteRequestHandler<MyRow> { }
");


            
            #line 51 "..\..\Views\EntityRepository.cshtml"
 if (Model.IsActiveField != null) {
            
            #line default
            #line hidden
WriteLiteral("\r\n        private class MyUndeleteHandler : UndeleteRequestHandler<MyRow> { }\r\n");


            
            #line 53 "..\..\Views\EntityRepository.cshtml"
       }

            
            #line default
            #line hidden
WriteLiteral("        private class MyRetrieveHandler : RetrieveRequestHandler<MyRow> { }\r\n    " +
"    private class MyListHandler : ListRequestHandler<MyRow> { }\r\n    }\r\n}");


        }
    }
}
#pragma warning restore 1591
