#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serenity.CodeGenerator.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class EntityCss : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 2 "..\..\Views\EntityCss.cshtml"
 public dynamic Model { get; set; } 
        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");


WriteLiteral("\r\n\r\n.s-");


            
            #line 4 "..\..\Views\EntityCss.cshtml"
Write(Model.ClassName);

            
            #line default
            #line hidden
WriteLiteral("Dialog {\r\n    > .size {\r\n        .widthAndMin(650px);\r\n    }\r\n    .dialog-styles(" +
"");


WriteLiteral("@h: auto, ");


WriteLiteral("@l: 150px, ");


WriteLiteral("@e: 400px);\r\n\r\n    .categories {\r\n    height: 260px;\r\n    }\r\n}");


        }
    }
}
#pragma warning restore 1591
