#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serenity.CodeGenerator.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class EntityRepository : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden
 public dynamic Model { get; set; } 
        public override void Execute()
        {


WriteLiteral("\r\n");



                                                   var dotModule = Model.Module == null ? "" : ("." + Model.Module);

WriteLiteral("\r\nnamespace ");


      Write(Model.RootNamespace);


                            Write(dotModule);

WriteLiteral(".Repositories\r\n{\r\n    using Serenity;\r\n    using Serenity.Data;\r\n    using Sereni" +
"ty.Services;\r\n    using System;\r\n    using System.Data;\r\n    using MyRow = Entit" +
"ies.");


                       Write(Model.RowClassName);

WriteLiteral(";\r\n\r\n    public class ");


             Write(Model.ClassName);

WriteLiteral(@"Repository
    {
        private static MyRow.RowFields fld { get { return MyRow.Fields; } }

        public SaveResponse Create(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            return new MySaveHandler().Process(uow, request, SaveRequestType.Create);
        }

        public SaveResponse Update(IUnitOfWork uow, SaveRequest<MyRow> request)
        {
            return new MySaveHandler().Process(uow, request, SaveRequestType.Update);
        }

        public DeleteResponse Delete(IUnitOfWork uow, DeleteRequest request)
        {
            return new MyDeleteHandler().Process(uow, request);
        }

");


 if (Model.IsActiveField != null) {

WriteLiteral("        public UndeleteResponse Undelete(IUnitOfWork uow, UndeleteRequest request" +
")\r\n        {\r\n            return new MyUndeleteHandler().Process(uow, request);\r" +
"\n        }\r\n");

WriteLiteral("\r\n");


}

WriteLiteral(@"        public RetrieveResponse<MyRow> Retrieve(IDbConnection connection, RetrieveRequest request)
        {
            return new MyRetrieveHandler().Process(connection, request);
        }

        public ListResponse<MyRow> List(IDbConnection connection, ListRequest request)
        {
            return new MyListHandler().Process(connection, request);
        }

        private class MySaveHandler : SaveRequestHandler<MyRow> { }
        private class MyDeleteHandler : DeleteRequestHandler<MyRow> { }
");


 if (Model.IsActiveField != null) {
WriteLiteral("\r\n        private class MyUndeleteHandler : UndeleteRequestHandler<MyRow> { }\r\n");


       }

WriteLiteral("        private class MyRetrieveHandler : RetrieveRequestHandler<MyRow> { }\r\n    " +
"    private class MyListHandler : ListRequestHandler<MyRow> { }\r\n    }\r\n}");


        }
    }
}
#pragma warning restore 1591
