#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serenity.CodeGenerator.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class EntityColumns : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden
 public dynamic Model { get; set; } 
        public override void Execute()
        {


WriteLiteral(Environment.NewLine);



                                                   
    var dotModule = Model.Module == null ? "" : ("." + Model.Module);
    var moduleDot = Model.Module == null ? "" : (Model.Module + ".");


WriteLiteral("namespace ");


      Write(Model.RootNamespace);


                            Write(dotModule);

WriteLiteral(".Columns" + Environment.NewLine + "{" + Environment.NewLine + "    using Serenity;" + Environment.NewLine + "    using Serenity.ComponentModel;" + Environment.NewLine + "    using S" +
"erenity.Data;" + Environment.NewLine + "    using System;" + Environment.NewLine + "    using System.ComponentModel;" + Environment.NewLine + "    using Sy" +
"stem.Collections.Generic;" + Environment.NewLine + "    using System.IO;" + Environment.NewLine + Environment.NewLine + "    [ColumnsScript(\"");


                Write(moduleDot);


                            Write(Model.ClassName);

WriteLiteral("\")]" + Environment.NewLine + "    [BasedOnRow(typeof(Entities.");


                            Write(Model.RowClassName);

WriteLiteral("))]" + Environment.NewLine + "    public class ");


             Write(Model.ClassName);


                                   WriteLiteral("Columns" + Environment.NewLine + "    {");

      foreach (EntityField x in Model.Fields) {
        var attrs = new List<string>();
        if (x.Ident == Model.IdField) {
            attrs.Add("EditLink");
            attrs.Add("DisplayName(\"Db.Shared.RecordId\")");
            attrs.Add("AlignRight");
        }
        else if (x.Ident == Model.NameField) {
            attrs.Add("EditLink");
        }
        if (attrs.Count > 0)
        {
WriteLiteral(Environment.NewLine + "        [");


    Write(string.Join(", ", attrs));

WriteLiteral("]");


                                          }
WriteLiteral(Environment.NewLine + "        public ");


          Write(x.DataType);

WriteLiteral(" ");


                      Write(x.Ident);

WriteLiteral(" { get; set; }");


                                                        }

WriteLiteral(Environment.NewLine + "    }" + Environment.NewLine + "}");


        }
    }
}
#pragma warning restore 1591
