#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serenity.CodeGenerator.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class EntityPageController : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden
 public dynamic Model { get; set; } 
        public override void Execute()
        {


WriteLiteral("\r\n");



                                                   
    var dotModule = Model.Module == null ? "" : ("." + Model.Module);
    var modulePath = Model.Module ?? Model.RootNamespace;
    var modulePrefix = (Model.Module == null ? "" : (Model.Module + "/"));


WriteLiteral("\r\n[assembly:Serenity.Navigation.NavigationLink(int.MaxValue, \"");


                                                        Write(modulePrefix);


                                                                       Write(Model.ClassName);

WriteLiteral("\", typeof(");


                                                                                                   Write(Model.RootNamespace);


                                                                                                                         Write(dotModule);

WriteLiteral(".Pages.");


                                                                                                                                            Write(Model.ClassName);

WriteLiteral("Controller))]\r\n\r\nnamespace ");


      Write(Model.RootNamespace);


                            Write(dotModule);

WriteLiteral(".Pages\r\n{\r\n    using Serenity;\r\n    using Serenity.Web;\r\n    using System.Web.Mvc" +
";\r\n\r\n    [RoutePrefix(\"");


              Write(modulePrefix);


                             Write(Model.ClassName);

WriteLiteral("\"), Route(\"{action=index}\")]\r\n    public class ");


             Write(Model.ClassName);

WriteLiteral("Controller : Controller\r\n    {\r\n        [PageAuthorize(\"");


                    Write(Model.Permission);

WriteLiteral("\")]\r\n        public ActionResult Index()\r\n        {\r\n            return View(\"~/M" +
"odules/");


                               Write(modulePath);

WriteLiteral("/");


                                             Write(Model.ClassName);

WriteLiteral("/");


                                                                Write(Model.ClassName);

WriteLiteral("Index.cshtml\");\r\n        }\r\n    }\r\n}");


        }
    }
}
#pragma warning restore 1591
