#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serenity.CodeGenerator.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class EntityScriptDialogTS : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden
 public dynamic Model { get; set; } 
        public override void Execute()
        {


WriteLiteral("\r\n");



                                                   
    var dotModule = Model.Module == null ? "" : ("." + Model.Module);
    var moduleDot = Model.Module == null ? "" : (Model.Module + ".");
    var moduleSlash = Model.Module == null ? "" : (Model.Module + "/");


WriteLiteral("namespace ");


      Write(Model.RootNamespace);


                            Write(dotModule);

WriteLiteral(" {\r\n    import D = Serenity.Decorators;\r\n\r\n    ");


WriteLiteral("@D.formKey(");


            Write(Model.ClassName);


                                  WriteLiteral("Form.formKey)");

                                                if (Model.Identity != null) {
WriteLiteral("\r\n    ");


WriteLiteral("@D.idProperty(");


               Write(Model.RowClassName);

WriteLiteral(".idProperty)");


                                                           }

WriteLiteral("\r\n    ");


WriteLiteral("@D.localTextPrefix(");


                    Write(Model.RowClassName);


                                             WriteLiteral(".localTextPrefix)");

                                                               if (Model.NameField != null){
WriteLiteral("\r\n    ");


WriteLiteral("@D.nameProperty(");


                 Write(Model.RowClassName);

WriteLiteral(".nameProperty)");


                                                               }

WriteLiteral("\r\n    ");


WriteLiteral("@D.service(");


            Write(Model.ClassName);

WriteLiteral("Service.baseUrl)\r\n    export class ");


             Write(Model.ClassName);

WriteLiteral("Dialog extends Serenity.EntityDialog<");


                                                                    Write(Model.RowClassName);

WriteLiteral(", any> {\r\n        protected form = new ");


                         Write(Model.ClassName);

WriteLiteral("Form(this.get_idPrefix());\r\n    }\r\n}");


        }
    }
}
#pragma warning restore 1591
