#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serenity.CodeGenerator.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class EntityPageIndex : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden
 public dynamic Model { get; set; } 
        public override void Execute()
        {


WriteLiteral("\r\n");



                                                   var dotModule = Model.Module == null ? "" : ("." + Model.Module);


WriteLiteral("@{\r\n    ViewBag.Title = Serenity.LocalText.Get(\"Db");


                                          Write(dotModule);

WriteLiteral(".");


                                                       Write(Model.ClassName);

WriteLiteral(".EntityPlural\");\r\n}\r\n\r\n<div id=\"GridDiv\"></div>\r\n\r\n<script type=\"text/javascript\"" +
">\r\n    jQuery(function () {\r\n        new ");


        Write(Model.RootNamespace);


                              Write(dotModule);

WriteLiteral(".");


                                           Write(Model.ClassName);

WriteLiteral("Grid($(\'#GridDiv\'), {}).init();\r\n\r\n        Q.initFullHeightGridPage($(\'#GridDiv\')" +
");\r\n    });\r\n</script>");


        }
    }
}
#pragma warning restore 1591
