#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serenity.CodeGenerator.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class EntityScriptService : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden
 public dynamic Model { get; set; } 
        public override void Execute()
        {


WriteLiteral("\r\n");



                                                   
    var dotModule = Model.Module == null ? "" : ("." + Model.Module); 
    var modulePrefix = (Model.Module == null ? "" : (Model.Module + "/"));


WriteLiteral("namespace ");


      Write(Model.RootNamespace);


                            Write(dotModule);

WriteLiteral("\r\n{\r\n    using jQueryApi;\r\n    using Serenity;\r\n    using System;\r\n    using Syst" +
"em.Collections;\r\n    using System.Collections.Generic;\r\n    using System.Runtime" +
".CompilerServices;\r\n\r\n    [Imported, PreserveMemberCase]\r\n    public partial cla" +
"ss ");


                     Write(Model.ClassName);

WriteLiteral("Service\r\n    {\r\n        [InlineConstant] public const string BaseUrl = \"");


                                                    Write(modulePrefix);


                                                                   Write(Model.ClassName);

WriteLiteral("\";\r\n\r\n        [InlineCode(\"Q.serviceRequest(\'");


                                   Write(modulePrefix);


                                                  Write(Model.ClassName);

WriteLiteral("/Create\', {request}, {onSuccess}, {options})\")]\r\n        public static jQueryXmlH" +
"ttpRequest Create(SaveRequest<");


                                                          Write(Model.RowClassName);

WriteLiteral("> request, Action<SaveResponse> onSuccess, ServiceCallOptions options = null)\r\n  " +
"      {\r\n            return null;\r\n        }\r\n\r\n        [InlineCode(\"Q.serviceRe" +
"quest(\'");


                                   Write(modulePrefix);


                                                  Write(Model.ClassName);

WriteLiteral("/Update\', {request}, {onSuccess}, {options})\")]\r\n        public static jQueryXmlH" +
"ttpRequest Update(SaveRequest<");


                                                          Write(Model.RowClassName);

WriteLiteral("> request, Action<SaveResponse> onSuccess, ServiceCallOptions options = null)\r\n  " +
"      {\r\n            return null;\r\n        }\r\n \r\n        [InlineCode(\"Q.serviceR" +
"equest(\'");


                                   Write(modulePrefix);


                                                  Write(Model.ClassName);

WriteLiteral("/Delete\', {request}, {onSuccess}, {options})\")]\r\n        public static jQueryXmlH" +
"ttpRequest Delete(DeleteRequest request, Action<DeleteResponse> onSuccess, Servi" +
"ceCallOptions options = null)\r\n        {\r\n            return null;\r\n        }\r\n\r" +
"\n");


 if (Model.IsActiveField != null) {

WriteLiteral("        [InlineCode(\"Q.serviceRequest(\'");


                                         Write(modulePrefix);


                                                        Write(Model.ClassName);

WriteLiteral("/Undelete\', {request}, {onSuccess}, {options})\")]\r\n        public static jQueryXm" +
"lHttpRequest Undelete(UndeleteRequest request, Action<UndeleteResponse> onSucces" +
"s, ServiceCallOptions options = null)\r\n        {\r\n            return null;\r\n    " +
"    }\r\n");

WriteLiteral("\r\n");


}

WriteLiteral("        [InlineCode(\"Q.serviceRequest(\'");


                                   Write(modulePrefix);


                                                  Write(Model.ClassName);

WriteLiteral("/Retrieve\', {request}, {onSuccess}, {options})\")]\r\n        public static jQueryXm" +
"lHttpRequest Retrieve(RetrieveRequest request, Action<RetrieveResponse<");


                                                                                                 Write(Model.RowClassName);

WriteLiteral(">> onSuccess, ServiceCallOptions options = null)\r\n        {\r\n            return n" +
"ull;\r\n        }\r\n\r\n        [InlineCode(\"Q.serviceRequest(\'");


                                   Write(modulePrefix);


                                                  Write(Model.ClassName);

WriteLiteral("/List\', {request}, {onSuccess}, {options})\")]\r\n        public static jQueryXmlHtt" +
"pRequest List(ListRequest request, Action<ListResponse<");


                                                                                     Write(Model.RowClassName);

WriteLiteral(">> onSuccess, ServiceCallOptions options = null)\r\n        {\r\n            return n" +
"ull;\r\n        }\r\n\r\n        [Imported, PreserveMemberCase]\r\n        public static" +
" class Methods\r\n        {\r\n            [InlineConstant] public const string Crea" +
"te = \"");


                                                       Write(modulePrefix);


                                                                      Write(Model.ClassName);

WriteLiteral("/Create\";\r\n            [InlineConstant] public const string Update = \"");


                                                       Write(modulePrefix);


                                                                      Write(Model.ClassName);

WriteLiteral("/Update\";\r\n            [InlineConstant] public const string Delete = \"");


                                                       Write(modulePrefix);


                                                                      Write(Model.ClassName);

WriteLiteral("/Delete\";\r\n");


 if (Model.IsActiveField != null) {

WriteLiteral("\r\n            [InlineConstant] public const string Undelete = \"");


                                                         Write(modulePrefix);


                                                                        Write(Model.ClassName);

WriteLiteral("/Undelete\";\r\n");

WriteLiteral("\r\n");


}

WriteLiteral("            [InlineConstant] public const string Retrieve = \"");


                                                         Write(modulePrefix);


                                                                        Write(Model.ClassName);

WriteLiteral("/Retrieve\";\r\n            [InlineConstant] public const string List = \"");


                                                     Write(modulePrefix);


                                                                    Write(Model.ClassName);

WriteLiteral("/List\";\r\n        }\r\n    }\r\n}");


        }
    }
}
#pragma warning restore 1591
