#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serenity.CodeGenerator.Views
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class EntityScriptGrid : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden
 public dynamic Model { get; set; } 
        public override void Execute()
        {


WriteLiteral("\r\n");



                                                   
    var dotModule = Model.Module == null ? "" : ("." + Model.Module);
    var moduleDot = Model.Module == null ? "" : (Model.Module + ".");
    var moduleSlash = Model.Module == null ? "" : (Model.Module + "/");


WriteLiteral("namespace ");


      Write(Model.RootNamespace);


                            Write(dotModule);

WriteLiteral("\r\n{\r\n    using jQueryApi;\r\n    using Serenity;\r\n    using System;\r\n    using Syst" +
"em.Collections.Generic;\r\n    using System.Runtime.CompilerServices;\r\n\r\n    [Colu" +
"mnsKey(\"");


             Write(moduleDot);


                         Write(Model.ClassName);

WriteLiteral("\"), IdProperty(\"");


                                                          Write(Model.Identity);


                                                                              WriteLiteral("\")");

                                                                                 if (Model.NameField != null){
WriteLiteral(", NameProperty(\"");


                                                                                                                               Write(Model.NameField);

WriteLiteral("\")");


                                                                                                                                                             }

                                                                                                                                                               if (Model.IsActiveField != null) {
WriteLiteral(", IsActiveProperty(\"");


                                                                                                                                                                                                                       Write(Model.IsActiveField);

WriteLiteral("\")");


                                                                                                                                                                                                                                                          }
WriteLiteral("]\r\n    [DialogType(typeof(");


                   Write(Model.ClassName);

WriteLiteral("Dialog)), LocalTextPrefix(\"");


                                                                Write(moduleDot);


                                                                            Write(Model.ClassName);

WriteLiteral("\"), Service(\"");


                                                                                                           Write(moduleSlash);


                                                                                                                         Write(Model.ClassName);

WriteLiteral("\")]\r\n    public class ");


             Write(Model.ClassName);

WriteLiteral("Grid : EntityGrid<");


                                                 Write(Model.RowClassName);

WriteLiteral(">\r\n    {\r\n        public ");


           Write(Model.ClassName);

WriteLiteral(@"Grid(jQueryObject container)
            : base(container)
        {
        }
    }

    // Please remove this partial class or the first line below, after you run ScriptContexts.tt
    [Imported, Serializable, PreserveMemberCase] 
    public partial class ");


                     Write(Model.ClassName);

WriteLiteral("Row\r\n    {\r\n    }\r\n}");


        }
    }
}
#pragma warning restore 1591
