namespace Serenity.Reflection;

public class CodeWriterTests
{
    [Fact]
    public void Ctor_Throws_ArgumentNull_If_StringBuilder_IsNull()
    {
        Assert.Throws<ArgumentNullException>(() => new CodeWriter(sb: null, tabSize: 4));
        Assert.Throws<ArgumentNullException>(() => new CodeWriter(sb: null, tab: "\t"));
    }

    [Fact]
    public void Ctor_Throws_ArgumentNull_If_TabString_IsNull()
    {
        Assert.Throws<ArgumentNullException>(() => new CodeWriter(new(), null));
    }

    [Fact]
    public void Ctor_Tab_Size_Is_4_ByDefault()
    {
        var cw = new CodeWriter();
        Assert.Equal("    ", cw.Tab);
    }

    [Fact]
    public void Ctor_Uses_Specified_Tab_String_As_Is()
    {
        var cw1 = new CodeWriter(new(), "\t");
        Assert.Equal("\t", cw1.Tab);
        var cw2 = new CodeWriter(new(), "@@@");
        Assert.Equal("@@@", cw2.Tab);
    }

    [Fact]
    public void ToString_Includes_AutoGenerated_Comment_When_Enabled()
    {
        var cw = new CodeWriter
        {
            AutoGeneratedComment = true
        };
        cw.Append("class Test { }");

        var actual = cw.ToString().Replace("\r", "");
        Assert.Equal("// <auto-generated />\n\nclass Test { }", actual);
    }

    [Fact]
    public void ToString_Includes_Custom_AutoGenerated_Comment_And_Pragma_Suppressions()
    {
        var cw = new CodeWriter
        {
            AutoGeneratedComment = true,
            AutoGeneratedCommentText = "// Generated file",
            PragmaSuppressions = { "CS1591", "CS0618" }
        };
        cw.AppendLine("class Test { }");

        var actual = cw.ToString().Replace("\r", "");
        Assert.Equal("// Generated file\n\n#pragma warning disable CS0618, CS1591\n\nclass Test { }\n\n#pragma warning restore CS0618, CS1591", actual);
    }

    [Fact]
    public void ToString_Adds_Pragma_Restore_At_End_When_Suppressions_Exist()
    {
        var cw = new CodeWriter
        {
            PragmaSuppressions = { "CS1591" }
        };
        cw.AppendLine("class Test { }");

        var actual = cw.ToString().Replace("\r", "");
        Assert.Equal("#pragma warning disable CS1591\n\nclass Test { }\n\n#pragma warning restore CS1591", actual);
    }

    [Fact]
    public void ToString_Does_Not_Add_Pragma_Restore_When_No_Suppressions()
    {
        var cw = new CodeWriter();
        cw.Append("class Test { }");

        var actual = cw.ToString().Replace("\r", "");
        Assert.Equal("class Test { }", actual);
        Assert.DoesNotContain("#pragma warning", actual);
    }

    [Fact]
    public void SuppressMissingXmlCommentWarning_Toggles_CS1591_Pragma()
    {
        var cw = new CodeWriter();

        Assert.False(cw.SuppressMissingXmlCommentWarning);
        cw.SuppressMissingXmlCommentWarning = true;
        Assert.True(cw.SuppressMissingXmlCommentWarning);
        var enabled = cw.ToString();
        Assert.Contains("#pragma warning disable CS1591", enabled);
        Assert.Contains("#pragma warning restore CS1591", enabled);

        cw.SuppressMissingXmlCommentWarning = false;
        Assert.False(cw.SuppressMissingXmlCommentWarning);
        var disabled = cw.ToString();
        Assert.DoesNotContain("#pragma warning disable", disabled);
        Assert.DoesNotContain("#pragma warning restore", disabled);
    }

    [Fact]
    public void Increase_Indent_Adds_One_Tab_String()
    {
        var cw = new CodeWriter(new(), "123");
        Assert.Equal("", cw.ToString());
        cw.IncreaseIndent();
        cw.Indented("X");
        Assert.Equal("123X", cw.ToString());
        cw.IncreaseIndent();
        cw.Indented("Y");
        Assert.Equal("123X123123Y", cw.ToString());
    }

    [Fact]
    public void Decrease_Indent_Removes_One_Tab_String()
    {
        var cw = new CodeWriter(new(), "123");
        cw.IncreaseIndent();
        cw.IncreaseIndent();
        cw.IncreaseIndent();
        cw.Indented("X");
        Assert.Equal("123123123X", cw.ToString());
        cw.DecreaseIndent();
        cw.Indented("Y");
        Assert.Equal("123123123X123123Y", cw.ToString());
        cw.DecreaseIndent();
        cw.Indented("Z");
        Assert.Equal("123123123X123123Y123Z", cw.ToString());
        cw.DecreaseIndent();
        cw.Indented("!");
        Assert.Equal("123123123X123123Y123Z!", cw.ToString());
    }

    [Fact]
    public void Decrease_Indent_Ignores_If_No_Current_Indent()
    {
        var cw = new CodeWriter(new(), "123");
        cw.IncreaseIndent();
        cw.IncreaseIndent();
        cw.DecreaseIndent();
        cw.DecreaseIndent();
        cw.DecreaseIndent();
        cw.Indented("Z");
        Assert.Equal("Z", cw.ToString());
    }

    [Fact]
    public void Block_Throws_ArgumentNull_If_Action_IsNull()
    {
        Assert.Throws<ArgumentNullException>(() => new CodeWriter().Block(insideBlock: null));
    }

    [Fact]
    public void Block_Increases_Indent_Calls_Action_Then_Decreases_Indent()
    {
        var cw = new CodeWriter(new(), "\t");
        cw.IndentedLine("A");
        cw.Block(() =>
        {
            cw.IndentedLine("X");
            cw.IndentedLine("Y");
        });
        cw.IndentedLine("B");

        var actual = cw.ToString().Replace("\r", "").TrimEnd();
        Assert.Equal("A\n\tX\n\tY\nB", actual);
    }

    [Fact]
    public void Block_CanBe_Nested()
    {
        var cw = new CodeWriter(new(), "\t");
        cw.IndentedLine("A");
        cw.Block(() =>
        {
            cw.IndentedLine("X");
            cw.Block(() =>
            {
                cw.IndentedLine("Y");
            });
            cw.IndentedLine("Z");
        });
        cw.IndentedLine("B");

        var actual = cw.ToString().Replace("\r", "").TrimEnd();
        Assert.Equal("A\n\tX\n\t\tY\n\tZ\nB", actual);
    }

    [Fact]
    public void InBrace_ThrowsArgumentNull_If_InsideBlock_IsNull()
    {
        Assert.Throws<ArgumentNullException>(() => new CodeWriter().InBrace(insideBlock: null, endLine: true));
        Assert.Throws<ArgumentNullException>(() => new CodeWriter().InBrace(insideBlock: null, endLine: false));
    }

    [Fact]
    public void InBrace_Prepends_SpaceBefore_If_BraceOnSameLine_IsTrue()
    {
        var cw = new CodeWriter(new(), tab: "\t")
        {
            BraceOnSameLine = true
        };
        cw.Append("A");
        cw.InBrace(() => cw.AppendLine("Test"));
        var actual = cw.ToString().Replace("\r", "").TrimEnd();
        Assert.Equal("A {\nTest\n}", actual);
    }

    [Fact]
    public void InBrace_Does_Not_Prepend_Space_If_BraceOnSameLine_IsFalse()
    {
        var cw = new CodeWriter(new(), tab: "\t")
        {
            BraceOnSameLine = false
        };
        cw.Append("A");
        cw.InBrace(() => cw.AppendLine("Test"));
        var actual = cw.ToString().Replace("\r", "").TrimEnd();
        Assert.Equal("A{\nTest\n}", actual);
    }

    [Fact]
    public void InBrace_Does_Not_EndLine_If_EndLine_IsFalse()
    {
        var cw = new CodeWriter(new(), tab: "\t")
        {
            BraceOnSameLine = false
        };
        cw.Append("A");
        cw.InBrace(() => cw.AppendLine("Test"), endLine: false);
        cw.Append("X");
        var actual = cw.ToString().Replace("\r", "").TrimEnd();
        Assert.Equal("A{\nTest\n}X", actual);
    }

    [Fact]
    public void InBrace_EndsLine_If_EndLine_IsTrue()
    {
        var cw = new CodeWriter(new(), tab: "\t")
        {
            BraceOnSameLine = false
        };
        cw.Append("A");
        cw.InBrace(() => cw.AppendLine("Test"), endLine: true);
        cw.Append("X");
        var actual = cw.ToString().Replace("\r", "").TrimEnd();
        Assert.Equal("A{\nTest\n}\nX", actual);
    }

    [Fact]
    public void InBrace_Increases_Indent_InsideTheBlock()
    {
        var cw = new CodeWriter(new(), tab: "\t")
        {
            BraceOnSameLine = false
        };
        cw.AppendLine("A");
        cw.InBrace(() => 
        {
            cw.IndentedLine("Test1");
            cw.IndentedLine("Test2");
        }, endLine: true);
        var actual = cw.ToString().Replace("\r", "").TrimEnd();
        Assert.Equal("A\n{\n\tTest1\n\tTest2\n}", actual);
    }

    [Fact]
    public void InBrace_Restores_Indent_AfterTheBlock()
    {
        var cw = new CodeWriter(new(), tab: "\t")
        {
            BraceOnSameLine = false
        };
        cw.AppendLine("A");
        cw.InBrace(() =>
        {
            cw.IndentedLine("Test1");
            cw.InBrace(() => cw.IndentedLine("Test2"));
            cw.IndentedLine("Test3");
        }, endLine: true);
        cw.IndentedLine("Test4");
        var actual = cw.ToString().Replace("\r", "").TrimEnd();
        Assert.Equal("A\n{\n\tTest1\n\t{\n\t\tTest2\n\t}\n\tTest3\n}\nTest4", actual);
    }

    [Fact]
    public void StartBrace_Prepends_SpaceBefore_If_BraceOnSameLine_IsTrue()
    {
        var cw = new CodeWriter(new(), tab: "\t")
        {
            BraceOnSameLine = true
        };
        cw.Append("A");
        cw.StartBrace();
        cw.Append("X");
        var actual = cw.ToString().Replace("\r", "").TrimEnd();
        Assert.Equal("A {\nX", actual);
    }

    [Fact]
    public void StartBrace_Does_Not_Prepend_Space_If_BraceOnSameLine_IsFalse()
    {
        var cw = new CodeWriter(new(), tab: "\t")
        {
            BraceOnSameLine = false
        };
        cw.Append("A");
        cw.StartBrace();
        cw.Append("X");
        var actual = cw.ToString().Replace("\r", "").TrimEnd();
        Assert.Equal("A{\nX", actual);
    }

    [Fact]
    public void EndBrace_Does_Not_EndLine_If_EndLine_IsFalse()
    {
        var cw = new CodeWriter(new(), tab: "\t")
        {
            BraceOnSameLine = false
        };
        cw.Append("A");
        cw.StartBrace();
        cw.Append("X");
        cw.EndBrace(endLine: false);
        cw.Append("Y");
        var actual = cw.ToString().Replace("\r", "").TrimEnd();
        Assert.Equal("A{\nX}Y", actual);
    }

    [Fact]
    public void EndBrace_EndsLine_If_EndLine_IsTrue()
    {
        var cw = new CodeWriter(new(), tab: "\t")
        {
            BraceOnSameLine = false
        };
        cw.Append("A");
        cw.StartBrace();
        cw.Append("X");
        cw.EndBrace(endLine: true);
        cw.Append("Y");
        var actual = cw.ToString().Replace("\r", "").TrimEnd();
        Assert.Equal("A{\nX}\nY", actual);
    }

    [Fact]
    public void StartBrace_Increases_Indent()
    {
        var cw = new CodeWriter(new(), tab: "\t")
        {
            BraceOnSameLine = false
        };
        cw.AppendLine("A");
        cw.StartBrace();
        cw.IndentedLine("Test1");
        cw.StartBrace();
        cw.IndentedLine("Test2");
        var actual = cw.ToString().Replace("\r", "").TrimEnd();
        Assert.Equal("A\n{\n\tTest1\n\t{\n\t\tTest2", actual);
    }

    [Fact]
    public void EndBrace_Decreases_Indent()
    {
        var cw = new CodeWriter(new(), tab: "\t")
        {
            BraceOnSameLine = false
        };
        cw.IncreaseIndent();
        cw.IndentedLine("X");
        cw.EndBrace();
        cw.IndentedLine("Y");
        var actual = cw.ToString().Replace("\r", "").TrimEnd();
        Assert.Equal("\tX\n}\nY", actual);
    }

    [Fact]
    public void Indent_Appends_CurrentIndent()
    {
        var cw = new CodeWriter(new(), tab: "\t");
        cw.Append("A");
        cw.Indent();
        cw.Append("B");
        cw.IncreaseIndent();
        cw.Indent();
        cw.Append("C");
        cw.IncreaseIndent();
        cw.Indent();
        cw.Append("D");
        cw.DecreaseIndent();
        cw.DecreaseIndent();
        cw.Indent();
        cw.Append("E");
        var actual = cw.ToString().Replace("\r", "").TrimEnd();
        Assert.Equal("AB\tC\t\tDE", actual);
    }

    [Fact]
    public void Indented_MultiLine_Ignores_EmptyString()
    {
        var cw = new CodeWriter(new(), tab: "\t");
        cw.IndentedLine("A");
        cw.IncreaseIndent();
        cw.IncreaseIndent();
        cw.IndentedMultiLine("");
        cw.DecreaseIndent();
        cw.IndentedLine("B");
        var actual = cw.ToString().Replace("\r", "").TrimEnd();
        Assert.Equal("A\n\tB", actual);
    }

    [Fact]
    public void Indented_MultiLine_Indents_Each_Line_By_Current_Indent()
    {
        var cw = new CodeWriter(new(), tab: "\t");
        cw.IndentedLine("A");
        cw.IncreaseIndent();
        cw.IncreaseIndent();
        cw.IndentedMultiLine("X\n\tY\n\t\tZ\nU\n");
        cw.DecreaseIndent();
        cw.IndentedLine("B");
        var actual = cw.ToString().Replace("\r", "").TrimEnd();
        Assert.Equal("A\n\t\tX\n\t\t\tY\n\t\t\t\tZ\n\t\tU\n\n\tB", actual);
    }

    [Fact]
    public void InNamespace_DoesNotOpen_An_Actual_Namespace_If_Passed_Null()
    {
        var cw = new CodeWriter(new(), tab: "\t")
        {
            CurrentNamespace = "X"
        };
        cw.InNamespace(null, () =>
        {
            cw.IndentedLine("Test");
            Assert.Null(cw.CurrentNamespace);
        });
        Assert.Equal("X", cw.CurrentNamespace);
        var actual = cw.ToString().Replace("\r", "").TrimEnd();
        Assert.Equal("Test", actual);
    }

    [Fact]
    public void InNamespace_DoesNotOpen_An_Actual_Namespace_If_Passed_EmptyString()
    {
        var cw = new CodeWriter(new(), tab: "\t")
        {
            CurrentNamespace = "X"
        };
        cw.InNamespace("", () =>
        {
            cw.IndentedLine("Test");
            Assert.Equal("", cw.CurrentNamespace);
        });
        Assert.Equal("X", cw.CurrentNamespace);
        var actual = cw.ToString().Replace("\r", "").TrimEnd();
        Assert.Equal("Test", actual);
    }

    [Fact]
    public void InNamespace_Opens_Namespace_With_Braced_Block()
    {
        var cw = new CodeWriter(new(), tab: "\t")
        {
            CurrentNamespace = "X",
            BraceOnSameLine = false
        };
        cw.InNamespace("Z", () =>
        {
            cw.IndentedLine("Test");
            Assert.Equal("Z", cw.CurrentNamespace);
        });
        cw.IndentedLine("Y");
        Assert.Equal("X", cw.CurrentNamespace);
        var actual = cw.ToString().Replace("\r", "").TrimEnd();
        Assert.Equal("namespace Z\n{\n\tTest\n}\nY", actual);
    }

    [Fact]
    public void InNamespace_Uses_Current_Indentation()
    {
        var cw = new CodeWriter(new(), tab: "\t")
        {
            CurrentNamespace = "X",
            BraceOnSameLine = false
        };
        cw.IncreaseIndent();
        cw.IncreaseIndent();
        cw.InNamespace("Z", () =>
        {
            cw.IndentedLine("Test");
            Assert.Equal("Z", cw.CurrentNamespace);
        });
        cw.DecreaseIndent();
        cw.IndentedLine("Y");
        Assert.Equal("X", cw.CurrentNamespace);
        var actual = cw.ToString().Replace("\r", "").TrimEnd();
        Assert.Equal("\t\tnamespace Z\n\t\t{\n\t\t\tTest\n\t\t}\n\tY", actual);
    }

    [Fact]
    public void InNamespace_Uses_FileScoped_Namespace_When_Enabled()
    {
        var cw = new CodeWriter(new(), tab: "\t")
        {
            CurrentNamespace = "X",
            FileScopedNamespaces = true,
            IsCSharp = true
        };
        cw.InNamespace("Z", () =>
        {
            cw.IndentedLine("Test");
            Assert.Equal("Z", cw.CurrentNamespace);
        });
        Assert.Equal("X", cw.CurrentNamespace);
        var actual = cw.ToString().Replace("\r", "").TrimEnd();
        Assert.Equal("namespace Z;\n\nTest", actual);
    }

    [Fact]
    public void InNamespace_DoesNotUseFileScoped_WhenNotCSharp()
    {
        var cw = new CodeWriter(new(), tab: "\t")
        {
            CurrentNamespace = "X",
            FileScopedNamespaces = true,
            IsCSharp = false
        };
        cw.InNamespace("Z", () => cw.IndentedLine("Test"));
        var actual = cw.ToString().Replace("\r", "").TrimEnd();
        Assert.Equal("namespace Z\n{\n\tTest\n}", actual);
    }

    [Fact]
    public void IsUsing_ReturnsTrue_ForCurrentNamespace()
    {
        var cw = new CodeWriter { CurrentNamespace = "Serenity" };
        Assert.True(cw.IsUsing("Serenity"));
    }

    [Fact]
    public void IsUsing_ReturnsTrue_ForGlobalUsings()
    {
        var cw = new CodeWriter { GlobalUsings = ["System"] };
        Assert.True(cw.IsUsing("System"));
    }

    [Fact]
    public void IsUsing_ReturnsTrue_ForLocalUsings()
    {
        var cw = new CodeWriter();
        cw.Using("System.IO", force: true);
        Assert.True(cw.IsUsing("System.IO"));
    }

    [Fact]
    public void IsUsing_ReturnsFalse_ForUnknownNamespace()
    {
        var cw = new CodeWriter();
        Assert.False(cw.IsUsing("Unknown"));
    }

    [Fact]
    public void Using_ReturnsTrue_WhenAlreadyUsed()
    {
        var cw = new CodeWriter { CurrentNamespace = "Serenity" };
        Assert.True(cw.Using("Serenity"));
    }

    [Fact]
    public void Using_AddsToLocalUsings_WhenAllowed()
    {
        var cw = new CodeWriter();
        Assert.True(cw.Using("System.IO"));
        Assert.Contains("System.IO", cw.LocalUsings);
    }

    [Fact]
    public void Using_Force_AddsEvenWhenNotAllowed()
    {
        var cw = new CodeWriter { AllowUsing = ns => false };
        Assert.True(cw.Using("System.IO", force: true));
        Assert.Contains("System.IO", cw.LocalUsings);
    }

    [Fact]
    public void Using_ReturnsFalse_WhenNotAllowed()
    {
        var cw = new CodeWriter { AllowUsing = ns => false };
        Assert.False(cw.Using("System.IO"));
        Assert.Null(cw.LocalUsings);
    }

    [Fact]
    public void ShortTypeName_ReturnsEmpty_ForEmptyTypeName()
    {
        var cw = new CodeWriter();
        Assert.Equal(string.Empty, cw.ShortTypeName("System", ""));
    }

    [Fact]
    public void ShortTypeName_ReturnsTypeName_ForEmptyNamespace()
    {
        var cw = new CodeWriter();
        Assert.Equal("String", cw.ShortTypeName("", "String"));
    }

    [Fact]
    public void ShortTypeName_ReturnsTypeName_WhenNamespaceUsed()
    {
        var cw = new CodeWriter();
        Assert.Equal("String", cw.ShortTypeName("System", "String"));
    }

    [Fact]
    public void ShortTypeName_ReturnsFullName_WhenNamespaceNotUsed()
    {
        var cw = new CodeWriter { AllowUsing = ns => false };
        Assert.Equal("System.String", cw.ShortTypeName("System", "String"));
    }

    [Fact]
    public void ShortTypeName_TrimsSharedRootNamespace()
    {
        var cw = new CodeWriter { CurrentNamespace = "Serenity.Data", AllowUsing = ns => false };
        Assert.Equal("Data.Mapping.Field", cw.ShortTypeName("Serenity.Data.Mapping", "Field"));
    }

    [Fact]
    public void ShortTypeName_FromFullName_ReturnsTypeName()
    {
        var cw = new CodeWriter();
        Assert.Equal("String", cw.ShortTypeName("System.String"));
    }

    [Fact]
    public void ShortTypeName_FromFullName_WithoutNamespace_ReturnsAsIs()
    {
        var cw = new CodeWriter();
        Assert.Equal("String", cw.ShortTypeName("String"));
    }

    [Fact]
    public void ShortTypeRef_ReturnsEmpty_ForEmptyString()
    {
        var cw = new CodeWriter();
        Assert.Equal(string.Empty, cw.ShortTypeRef(""));
    }

    [Fact]
    public void ShortTypeRef_HandlesNullableSuffix()
    {
        var cw = new CodeWriter { IsCSharp = true };
        Assert.Equal("int?", cw.ShortTypeRef("int?"));
    }

    [Fact]
    public void ShortTypeRef_ReturnsKeyword_ForCSharpPrimitive()
    {
        var cw = new CodeWriter { IsCSharp = true };
        Assert.Equal("string", cw.ShortTypeRef("string"));
    }

    [Fact]
    public void ShortTypeRef_MapsStream_ToSystemIOStream()
    {
        var cw = new CodeWriter { IsCSharp = true, AllowUsing = ns => false };
        Assert.Equal("System.IO.Stream", cw.ShortTypeRef("Stream"));
    }

    [Fact]
    public void ShortTypeRef_ResolvesSystemType()
    {
        var cw = new CodeWriter { IsCSharp = true, AllowUsing = ns => false };
        Assert.Equal("System.Int32", cw.ShortTypeRef("Int32"));
    }

    [Fact]
    public void ShortTypeRef_ReturnsAsIs_ForUnknownType()
    {
        var cw = new CodeWriter { IsCSharp = true };
        Assert.Equal("SomeUnknownType", cw.ShortTypeRef("SomeUnknownType"));
    }

    [Fact]
    public void ShortTypeRef_HandlesGenericTypes()
    {
        var cw = new CodeWriter { IsCSharp = true };
        Assert.Equal("List<String>", cw.ShortTypeRef("System.Collections.Generic.List<System.String>"));
    }

    [Fact]
    public void ShortTypeRef_NonCSharp_UsesShortTypeName()
    {
        var cw = new CodeWriter { IsCSharp = false };
        Assert.Equal("String", cw.ShortTypeRef("System.String"));
    }

    [Fact]
    public void IsCSKeyword_ReturnsTrue_ForKeywords()
    {
        Assert.True(CodeWriter.IsCSKeyword("string"));
        Assert.True(CodeWriter.IsCSKeyword("int"));
        Assert.True(CodeWriter.IsCSKeyword("bool"));
    }

    [Fact]
    public void IsCSKeyword_ReturnsFalse_ForNonKeywords()
    {
        Assert.False(CodeWriter.IsCSKeyword("String"));
        Assert.False(CodeWriter.IsCSKeyword("MyType"));
    }

    [Fact]
    public void IsJSKeyword_ReturnsTrue_ForReservedWords()
    {
        Assert.True(CodeWriter.IsJSKeyword("class"));
        Assert.True(CodeWriter.IsJSKeyword("function"));
        Assert.True(CodeWriter.IsJSKeyword("var"));
    }

    [Fact]
    public void IsJSKeyword_ReturnsFalse_ForNonReservedWords()
    {
        Assert.False(CodeWriter.IsJSKeyword("myVariable"));
    }

    [Fact]
    public void ToCSKeyword_ReturnsKeyword_ForPrimitiveClassNames()
    {
        Assert.Equal("string", CodeWriter.ToCSKeyword("String"));
        Assert.Equal("int", CodeWriter.ToCSKeyword("Int32"));
        Assert.Equal("bool", CodeWriter.ToCSKeyword("Boolean"));
    }

    [Fact]
    public void ToCSKeyword_ReturnsNull_ForNonPrimitive()
    {
        Assert.Null(CodeWriter.ToCSKeyword("MyType"));
    }

    [Fact]
    public void AppendLine_AppendsLine()
    {
        var cw = new CodeWriter();
        cw.AppendLine("Test");
        Assert.Equal("Test", cw.ToString());
    }

    [Fact]
    public void Append_AppendsText()
    {
        var cw = new CodeWriter();
        cw.Append("Test");
        Assert.Equal("Test", cw.ToString());
    }

    [Fact]
    public void Append_Char_AppendsChar()
    {
        var cw = new CodeWriter();
        cw.Append('X');
        Assert.Equal("X", cw.ToString());
    }

    [Fact]
    public void Insert_InsertsText()
    {
        var cw = new CodeWriter();
        cw.Append("AB");
        cw.Insert(1, "X");
        Assert.Equal("AXB", cw.ToString());
    }

    [Fact]
    public void ToString_Includes_FileComment()
    {
        var cw = new CodeWriter { FileComment = "// comment" };
        cw.Append("class Test { }");
        var actual = cw.ToString().Replace("\r", "");
        Assert.Equal("// comment\n\nclass Test { }", actual);
    }

    [Fact]
    public void ToString_Includes_LocalUsings()
    {
        var cw = new CodeWriter();
        cw.Using("System.IO");
        cw.Using("System.Text");
        cw.Append("class Test { }");
        var actual = cw.ToString().Replace("\r", "");
        Assert.Equal("using System.IO;\nusing System.Text;\n\nclass Test { }", actual);
    }

    [Fact]
    public void SafeSetOfUsings_ContainsCommonNamespaces()
    {
        Assert.Contains("Serenity", CodeWriter.SafeSetOfUsings);
        Assert.Contains("System", CodeWriter.SafeSetOfUsings);
        Assert.Contains("System.Collections.Generic", CodeWriter.SafeSetOfUsings);
    }
}