// <auto-generated />

namespace Serenity.Demo.Northwind;

/// <summary>An attribute that sets the editor type to <c>Serenity.Demo.Northwind.PhoneEditor</c> and its options.</summary>
public partial class PhoneEditorAttribute : CustomEditorAttribute
{
    /// <summary>The editor type key.</summary>
    public const string Key = "Serenity.Demo.Northwind.PhoneEditor";

    /// <summary>Creates a new instance of the <c>PhoneEditorAttribute</c> class.</summary>
    public PhoneEditorAttribute()
        : base(Key)
    {
    }

    /// <summary>Gets or sets the <c>multiple</c> option.</summary>
    public bool Multiple
    {
        get { return GetOption<bool>("multiple"); }
        set { SetOption("multiple", value); }
    }
}