// <auto-generated />

namespace Serenity.Demo.Northwind;

/// <summary>An attribute that sets the formatter type to <c>Serenity.Demo.Northwind.EmployeeListFormatter</c> and its options.</summary>
public partial class EmployeeListFormatterAttribute : CustomFormatterAttribute
{
    /// <summary>The formatter type key.</summary>
    public const string Key = "Serenity.Demo.Northwind.EmployeeListFormatter";

    /// <summary>Creates a new instance of the <c>EmployeeListFormatterAttribute</c> class.</summary>
    public EmployeeListFormatterAttribute()
        : base(Key)
    {
    }
}