// <auto-generated />

namespace Serenity.Demo.Northwind;

/// <summary>An attribute that sets the formatter type to <c>Serenity.Demo.Northwind.FreightFormatter</c> and its options.</summary>
public partial class FreightFormatterAttribute : CustomFormatterAttribute
{
    /// <summary>The formatter type key.</summary>
    public const string Key = "Serenity.Demo.Northwind.FreightFormatter";

    /// <summary>Creates a new instance of the <c>FreightFormatterAttribute</c> class.</summary>
    public FreightFormatterAttribute()
        : base(Key)
    {
    }
}