// <auto-generated />

namespace Serenity.Demo.Northwind;

/// <summary>An attribute that sets the editor type to <c>Serenity.Demo.Northwind.NotesEditor</c> and its options.</summary>
public partial class NotesEditorAttribute : CustomEditorAttribute
{
    /// <summary>The editor type key.</summary>
    public const string Key = "Serenity.Demo.Northwind.NotesEditor";

    /// <summary>Creates a new instance of the <c>NotesEditorAttribute</c> class.</summary>
    public NotesEditorAttribute()
        : base(Key)
    {
    }
}