// <auto-generated />

namespace Serenity.Demo.Northwind;

/// <summary>An attribute that sets the editor type to <c>Serenity.Demo.Northwind.OrderDetailsEditor</c> and its options.</summary>
public partial class OrderDetailsEditorAttribute : CustomEditorAttribute
{
    /// <summary>The editor type key.</summary>
    public const string Key = "Serenity.Demo.Northwind.OrderDetailsEditor";

    /// <summary>Creates a new instance of the <c>OrderDetailsEditorAttribute</c> class.</summary>
    public OrderDetailsEditorAttribute()
        : base(Key)
    {
    }
}