// <auto-generated />

namespace Serenity.Demo.Northwind;

/// <summary>An attribute that sets the formatter type to <c>Serenity.Demo.Northwind.ShipperFormatter</c> and its options.</summary>
public partial class ShipperFormatterAttribute : CustomFormatterAttribute
{
    /// <summary>The formatter type key.</summary>
    public const string Key = "Serenity.Demo.Northwind.ShipperFormatter";

    /// <summary>Creates a new instance of the <c>ShipperFormatterAttribute</c> class.</summary>
    public ShipperFormatterAttribute()
        : base(Key)
    {
    }
}