// <auto-generated />

namespace Serenity.Demo.Northwind;

/// <summary>An attribute that sets the formatter type to <c>Serenity.Demo.Northwind.EmployeeFormatter</c> and its options.</summary>
public partial class EmployeeFormatterAttribute : CustomFormatterAttribute
{
    /// <summary>The formatter type key.</summary>
    public const string Key = "Serenity.Demo.Northwind.EmployeeFormatter";

    /// <summary>Creates a new instance of the <c>EmployeeFormatterAttribute</c> class.</summary>
    public EmployeeFormatterAttribute()
        : base(Key)
    {
    }

    /// <summary>Gets or sets the <c>genderProperty</c> option.</summary>
    public string GenderProperty
    {
        get { return GetOption<string>("genderProperty"); }
        set { SetOption("genderProperty", value); }
    }
}