// <auto-generated />

namespace Serenity.Demo.Northwind;

/// <summary>An attribute that sets the editor type to <c>Serenity.Demo.Northwind.CustomerEditor</c> and its options.</summary>
public partial class CustomerEditorAttribute : LookupEditorBaseAttribute
{
    /// <summary>The editor type key.</summary>
    public const string Key = "Serenity.Demo.Northwind.CustomerEditor";

    /// <summary>Creates a new instance of the <c>CustomerEditorAttribute</c> class.</summary>
    public CustomerEditorAttribute()
        : base(Key)
    {
    }
}