// <auto-generated />

namespace Serenity.Extensions;

/// <summary>An attribute that sets the formatter type to <c>Serenity.Extensions.DeleteRowActionFormatter</c> and its options.</summary>
public partial class DeleteRowActionFormatterAttribute : CustomFormatterAttribute
{
    /// <summary>The formatter type key.</summary>
    public const string Key = "Serenity.Extensions.DeleteRowActionFormatter";

    /// <summary>Creates a new instance of the <c>DeleteRowActionFormatterAttribute</c> class.</summary>
    public DeleteRowActionFormatterAttribute()
        : base(Key)
    {
    }
}