// <auto-generated />

namespace Serenity.Extensions;

/// <summary>An attribute that sets the formatter type to <c>Serenity.Extensions.EnumSelectFormatter</c> and its options.</summary>
public partial class EnumSelectFormatterAttribute : CustomFormatterAttribute
{
    /// <summary>The formatter type key.</summary>
    public const string Key = "Serenity.Extensions.EnumSelectFormatter";

    /// <summary>Creates a new instance of the <c>EnumSelectFormatterAttribute</c> class.</summary>
    public EnumSelectFormatterAttribute()
        : base(Key)
    {
    }

    /// <summary>Gets or sets the <c>allowClear</c> option.</summary>
    public bool AllowClear
    {
        get { return GetOption<bool>("allowClear"); }
        set { SetOption("allowClear", value); }
    }

    /// <summary>Gets or sets the <c>emptyItemText</c> option.</summary>
    public string EmptyItemText
    {
        get { return GetOption<string>("emptyItemText"); }
        set { SetOption("emptyItemText", value); }
    }

    /// <summary>Gets or sets the <c>enumKey</c> option.</summary>
    public string EnumKey
    {
        get { return GetOption<string>("enumKey"); }
        set { SetOption("enumKey", value); }
    }
}