// <auto-generated />

namespace Serenity.Extensions;

/// <summary>An attribute that sets the editor type to <c>Serenity.Extensions.StaticTextBlock</c> and its options.</summary>
public partial class StaticTextBlockAttribute : CustomEditorAttribute
{
    /// <summary>The editor type key.</summary>
    public const string Key = "Serenity.Extensions.StaticTextBlock";

    /// <summary>Creates a new instance of the <c>StaticTextBlockAttribute</c> class.</summary>
    public StaticTextBlockAttribute()
        : base(Key)
    {
    }

    /// <summary>Gets or sets the <c>hideLabel</c> option.</summary>
    public bool HideLabel
    {
        get { return GetOption<bool>("hideLabel"); }
        set { SetOption("hideLabel", value); }
    }

    /// <summary>Gets or sets the <c>isHtml</c> option.</summary>
    public bool IsHtml
    {
        get { return GetOption<bool>("isHtml"); }
        set { SetOption("isHtml", value); }
    }

    /// <summary>Gets or sets the <c>isLocalText</c> option.</summary>
    public bool IsLocalText
    {
        get { return GetOption<bool>("isLocalText"); }
        set { SetOption("isLocalText", value); }
    }

    /// <summary>Gets or sets the <c>text</c> option.</summary>
    public string Text
    {
        get { return GetOption<string>("text"); }
        set { SetOption("text", value); }
    }
}