// <auto-generated />

namespace Serenity.Extensions;

/// <summary>An attribute that sets the formatter type to <c>Serenity.Extensions.SingleLineTextFormatter</c> and its options.</summary>
public partial class SingleLineTextFormatterAttribute : CustomFormatterAttribute
{
    /// <summary>The formatter type key.</summary>
    public const string Key = "Serenity.Extensions.SingleLineTextFormatter";

    /// <summary>Creates a new instance of the <c>SingleLineTextFormatterAttribute</c> class.</summary>
    public SingleLineTextFormatterAttribute()
        : base(Key)
    {
    }
}