// <auto-generated />

namespace Serenity.Extensions;

/// <summary>A class that mirrors the <c>ResetPasswordOptions</c> script type.</summary>
public partial class ResetPasswordOptions
{
    /// <summary>Gets or sets the <c>minPasswordLength</c> property.</summary>
    public double minPasswordLength { get; set; }

    /// <summary>Gets or sets the <c>token</c> property.</summary>
    public string token { get; set; }
}