namespace Serenity.CodeGenerator;

public partial class MvcCommandTests
{
    [Fact]
    public void SameSubFolderNameInDifferentParents()
    {
        var expected = /*lang=c#*/ """
            // <auto-generated />

            namespace MyTest
            {
                public static partial class MVC
                {
                    /// <summary>Provides paths to view files.</summary>
                    public static partial class Views
                    {
                        /// <summary>Provides view paths in the <c>MyModule</c> folder.</summary>
                        public static partial class MyModule
                        {
                            /// <summary>Provides view paths in the <c>MyModule/A</c> folder.</summary>
                            public static partial class A
                            {
                                /// <summary>Provides view paths in the <c>MyModule/A/Same</c> folder.</summary>
                                public static partial class Same
                                {
                                    /// <summary>The path to the <c>A1</c> view.</summary>
                                    public const string A1 = "~/Modules/MyModule/A/Same/A1.cshtml";
                                    /// <summary>The path to the <c>A2</c> view.</summary>
                                    public const string A2 = "~/Modules/MyModule/A/Same/A2.cshtml";
                                    /// <summary>The path to the <c>A3</c> view.</summary>
                                    public const string A3 = "~/Modules/MyModule/A/Same/A3.cshtml";
                                }
                            }

                            /// <summary>Provides view paths in the <c>MyModule/B</c> folder.</summary>
                            public static partial class B
                            {
                                /// <summary>Provides view paths in the <c>MyModule/B/Same</c> folder.</summary>
                                public static partial class Same
                                {
                                    /// <summary>The path to the <c>B1</c> view.</summary>
                                    public const string B1 = "~/Modules/MyModule/B/Same/B1.cshtml";
                                    /// <summary>The path to the <c>B2</c> view.</summary>
                                    public const string B2 = "~/Modules/MyModule/B/Same/B2.cshtml";
                                }
                            }
                        }
                    }
                }
            }
            """.ReplaceLineEndings();

        var command = CreateCommand(new GeneratorConfig(), [
            "Modules/MyModule/A/Same/A1.cshtml",
            "Modules/MyModule/A/Same/A2.cshtml",
            "Modules/MyModule/A/Same/A3.cshtml",
            "Modules/MyModule/B/Same/B1.cshtml",
            "Modules/MyModule/B/Same/B2.cshtml"], out var fileSystem);

        Assert.Equal(ExitCodes.Success, command.Run());

        Assert.Equal(expected, ReadMvc(fileSystem).Trim().ReplaceLineEndings());
    }
}
