namespace Serenity.CodeGenerator;

public partial class MvcCommandTests
{
    [Fact]
    public void Generates_EsmFile_With_DefaultEntryPoints()
    {
        var command = CreateCommand(new GeneratorConfig(),
            ["Modules/Admin/TestPage.ts"], out var fileSystem);

        Assert.Equal(ExitCodes.Success, command.Run());

        var esm = ReadEsm(fileSystem);
        Assert.StartsWith("// <auto-generated />", esm);
        Assert.Contains("public static partial class ESM", esm);
        Assert.Contains("public const string TestPage = \"~/esm/Modules/Admin/TestPage.js\";", esm);
    }
}
