namespace Serenity.CodeGenerator;

public partial class MvcCommandTests
{
    [Fact]
    public void Writes_AutoGeneratedComment()
    {
        var command = CreateCommand(new GeneratorConfig(),
            ["Modules/Admin/UserIndex.cshtml"], out var fileSystem);

        Assert.Equal(ExitCodes.Success, command.Run());

        Assert.StartsWith("// <auto-generated />", ReadMvc(fileSystem));
    }
}
