// <auto-generated />

namespace Serenity.Demo.Northwind.MVC;

/// <summary>Provides paths to ECMAScript module entry points.</summary>
public static partial class ESM
{
    /// <summary>The module path for the <c>CategoryPage</c> entry point.</summary>
    public const string CategoryPage = "~/Serenity.Demo.Northwind/esm/Modules/Category/CategoryPage.js";
    /// <summary>The module path for the <c>CustomerPage</c> entry point.</summary>
    public const string CustomerPage = "~/Serenity.Demo.Northwind/esm/Modules/Customer/CustomerPage.js";
    /// <summary>The module path for the <c>OrderPage</c> entry point.</summary>
    public const string OrderPage = "~/Serenity.Demo.Northwind/esm/Modules/Order/OrderPage.js";
    /// <summary>The module path for the <c>ProductPage</c> entry point.</summary>
    public const string ProductPage = "~/Serenity.Demo.Northwind/esm/Modules/Product/ProductPage.js";
    /// <summary>The module path for the <c>RegionPage</c> entry point.</summary>
    public const string RegionPage = "~/Serenity.Demo.Northwind/esm/Modules/Region/RegionPage.js";
    /// <summary>The module path for the <c>ShipperPage</c> entry point.</summary>
    public const string ShipperPage = "~/Serenity.Demo.Northwind/esm/Modules/Shipper/ShipperPage.js";
    /// <summary>The module path for the <c>SupplierPage</c> entry point.</summary>
    public const string SupplierPage = "~/Serenity.Demo.Northwind/esm/Modules/Supplier/SupplierPage.js";
    /// <summary>The module path for the <c>TerritoryPage</c> entry point.</summary>
    public const string TerritoryPage = "~/Serenity.Demo.Northwind/esm/Modules/Territory/TerritoryPage.js";

    /// <summary>Provides module entry points in the <c>Modules</c> folder.</summary>
    public static partial class Modules
    {
        /// <summary>Provides module entry points in the <c>Modules/Category</c> folder.</summary>
        public static partial class Category
        {
            /// <summary>The module path for the <c>CategoryPage</c> entry point.</summary>
            public const string CategoryPage = "~/Serenity.Demo.Northwind/esm/Modules/Category/CategoryPage.js";
        }

        /// <summary>Provides module entry points in the <c>Modules/Customer</c> folder.</summary>
        public static partial class Customer
        {
            /// <summary>The module path for the <c>CustomerPage</c> entry point.</summary>
            public const string CustomerPage = "~/Serenity.Demo.Northwind/esm/Modules/Customer/CustomerPage.js";
        }

        /// <summary>Provides module entry points in the <c>Modules/Order</c> folder.</summary>
        public static partial class Order
        {
            /// <summary>The module path for the <c>OrderPage</c> entry point.</summary>
            public const string OrderPage = "~/Serenity.Demo.Northwind/esm/Modules/Order/OrderPage.js";
        }

        /// <summary>Provides module entry points in the <c>Modules/Product</c> folder.</summary>
        public static partial class Product
        {
            /// <summary>The module path for the <c>ProductPage</c> entry point.</summary>
            public const string ProductPage = "~/Serenity.Demo.Northwind/esm/Modules/Product/ProductPage.js";
        }

        /// <summary>Provides module entry points in the <c>Modules/Region</c> folder.</summary>
        public static partial class Region
        {
            /// <summary>The module path for the <c>RegionPage</c> entry point.</summary>
            public const string RegionPage = "~/Serenity.Demo.Northwind/esm/Modules/Region/RegionPage.js";
        }

        /// <summary>Provides module entry points in the <c>Modules/Shipper</c> folder.</summary>
        public static partial class Shipper
        {
            /// <summary>The module path for the <c>ShipperPage</c> entry point.</summary>
            public const string ShipperPage = "~/Serenity.Demo.Northwind/esm/Modules/Shipper/ShipperPage.js";
        }

        /// <summary>Provides module entry points in the <c>Modules/Supplier</c> folder.</summary>
        public static partial class Supplier
        {
            /// <summary>The module path for the <c>SupplierPage</c> entry point.</summary>
            public const string SupplierPage = "~/Serenity.Demo.Northwind/esm/Modules/Supplier/SupplierPage.js";
        }

        /// <summary>Provides module entry points in the <c>Modules/Territory</c> folder.</summary>
        public static partial class Territory
        {
            /// <summary>The module path for the <c>TerritoryPage</c> entry point.</summary>
            public const string TerritoryPage = "~/Serenity.Demo.Northwind/esm/Modules/Territory/TerritoryPage.js";
        }
    }
}