// <auto-generated />

namespace Serenity.Demo.Northwind.MVC;

/// <summary>Provides paths to view files.</summary>
public static partial class Views
{
    /// <summary>Provides view paths in the <c>Order</c> folder.</summary>
    public static partial class Order
    {
        /// <summary>The path to the <c>OrderDetailReport</c> view.</summary>
        public const string OrderDetailReport = "~/Areas/Serenity.Demo.Northwind/Order/OrderDetailReport.cshtml";
        /// <summary>The path to the <c>OrderIndex</c> view.</summary>
        public const string OrderIndex = "~/Areas/Serenity.Demo.Northwind/Order/OrderIndex.cshtml";
    }

    /// <summary>Provides view paths in the <c>Product</c> folder.</summary>
    public static partial class Product
    {
        /// <summary>The path to the <c>ProductIndex</c> view.</summary>
        public const string ProductIndex = "~/Areas/Serenity.Demo.Northwind/Product/ProductIndex.cshtml";
    }
}