<Project>
  <ItemGroup>
    <PackageReference Include="FirebirdSql.Data.FirebirdClient" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="MySqlConnector" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" />
  </ItemGroup>
</Project>