// <autogenerated />
using Microsoft.Build.Framework;
using Microsoft.Build.Tasks;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Globalization;
using System.IO;
using System.Text;
using System.Threading;
using System.Transactions;

public class MutexExec : Exec
{
    [Required]
    public string MutexName { get; set; }
    public int MutexTimeout { get; set; } = 60000;
    public bool MutexWarningOnly { get; set; } = false;

    public bool Success = true;

    /// <inheritdoc />
    public override bool Execute()
    {
        var tryTimes = 3;
        var tryCount = 0;
        using (var mutex = new Mutex(initiallyOwned: false, MutexName))
        {
            try
            {
                while (true)
                {
                    Log.LogMessage(MessageImportance.High, $"Waiting to acquire Exec mutex {MutexName}...");
                    if (!mutex.WaitOne(MutexTimeout / tryTimes))
                    {
                        tryCount++;
                        if (tryCount > tryTimes) {
                            if (MutexWarningOnly)
                            {
                                Log.LogWarning($"Continuing execution despite failure to acquire Exec mutex {MutexName} due to MutexWarningOnly being set.");
                                break;
                            }
                            Log.LogError($"Failed to acquire Exec mutex {MutexName} after {tryCount} attempts.");
                            return false;
                        }
                        else {
                            Log.LogWarning($"Waiting to acquire Exec mutex {MutexName} timed out {tryCount}nd time...");
                        }
                    }
                    else
                    {
                        Log.LogMessage(MessageImportance.Normal, $"Acquired Exec mutex {MutexName}");
                        break;
                    }
                }
            }
            catch (AbandonedMutexException)
            {
                Log.LogMessage(MessageImportance.High, $"Acquired abandoned Exec mutex {MutexName}");
                // We got the mutex even though it was abandoned.
            }

            try
            {
                return base.Execute();
            }
            finally
            {
                mutex.ReleaseMutex();
            }
        }
    }
}
