
namespace Serenity.Data.Schema;

[Trait("tag", "sqldb")]
public partial class SchemaProviderIntegrationTests_Oracle
{
    [Fact]
    public void OracleSchemaProvider_Reads_Columns_Identity_Keys_ForeignKeys_And_Views()
    {
        var suffix = Guid.NewGuid().ToString("N")[..8].ToUpperInvariant();
        var parentTable = "SIT_P_" + suffix;
        var childTable = "SIT_C_" + suffix;
        var view = "SIT_V_" + suffix;
        var primaryKey = "SIT_PK_" + suffix;
        var foreignKey = "SIT_FK_" + suffix;
        var createdParent = false;
        var createdChild = false;
        var createdView = false;

        using var connection = SqlIntegrationConnections.CreateConnection("Oracle");
        connection.Open();
        try
        {
            SqlIntegrationConnections.ExecuteSql(connection, $"""
                CREATE TABLE {parentTable} (
                    PARENT_ID NUMBER(10) NOT NULL PRIMARY KEY,
                    NAME VARCHAR2(32)
                )
                """);
            createdParent = true;

            SqlIntegrationConnections.ExecuteSql(connection, $"""
                CREATE TABLE {childTable} (
                    ID NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    PARENT_ID NUMBER(10) NOT NULL,
                    AMOUNT NUMBER(10,2) NOT NULL,
                    CONSTRAINT {primaryKey} PRIMARY KEY (ID),
                    CONSTRAINT {foreignKey} FOREIGN KEY (PARENT_ID)
                        REFERENCES {parentTable}(PARENT_ID)
                )
                """);
            createdChild = true;

            SqlIntegrationConnections.ExecuteSql(connection, $"CREATE VIEW {view} AS SELECT ID, PARENT_ID FROM {childTable}");
            createdView = true;

            var schema = connection.Query<string>("SELECT USER FROM DUAL").Single();
            var provider = new OracleSchemaProvider();
            var fields = provider.GetFieldInfos(connection, schema, childTable).ToList();
            Assert.Equal(["ID", "PARENT_ID", "AMOUNT"], fields.Select(x => x.FieldName));
            Assert.Contains(fields, x => x.FieldName == "AMOUNT" && x.DataType == "NUMBER" && x.Size == 10 && x.Scale == 2);

            Assert.Equal(["ID"], provider.GetIdentityFields(connection, schema, childTable).ToList());
            Assert.Equal(["ID"], provider.GetPrimaryKeyFields(connection, schema, childTable).ToList());

            var foreignKeyInfo = Assert.Single(provider.GetForeignKeys(connection, schema, childTable));
            Assert.Equal(foreignKey, foreignKeyInfo.FKName);
            Assert.Equal("PARENT_ID", foreignKeyInfo.FKColumn);
            Assert.Equal(schema, foreignKeyInfo.PKSchema);
            Assert.Equal(parentTable, foreignKeyInfo.PKTable);
            Assert.Equal("PARENT_ID", foreignKeyInfo.PKColumn);

            var objects = provider.GetTableNames(connection)
                .Where(x => x.Schema == schema && (x.Table == parentTable || x.Table == childTable || x.Table == view))
                .ToDictionary(x => x.Table);
            Assert.Equal(3, objects.Count);
            Assert.False(objects[parentTable].IsView);
            Assert.False(objects[childTable].IsView);
            Assert.True(objects[view].IsView);
        }
        finally
        {
            try
            {
                if (createdView)
                    SqlIntegrationConnections.ExecuteSql(connection, $"DROP VIEW {view}");
            }
            finally
            {
                try
                {
                    if (createdChild)
                        SqlIntegrationConnections.ExecuteSql(connection, $"DROP TABLE {childTable} CASCADE CONSTRAINTS PURGE");
                }
                finally
                {
                    if (createdParent)
                        SqlIntegrationConnections.ExecuteSql(connection, $"DROP TABLE {parentTable} CASCADE CONSTRAINTS PURGE");
                }
            }
        }
    }
}
