namespace Serenity.Data.Schema;

[Trait("tag", "sqldb")]
public partial class SchemaProviderIntegrationTests_Postgres
{
    [Fact]
    public void PostgresSchemaProvider_Reads_Columns_Identity_Keys_ForeignKeys_And_Views()
    {
        var schema = "serenity_schema_it_" + Guid.NewGuid().ToString("N");
        var parentTable = "parent_" + Guid.NewGuid().ToString("N");
        var childTable = "child_" + Guid.NewGuid().ToString("N");
        var view = "view_" + Guid.NewGuid().ToString("N");
        var constraint = "fk_" + Guid.NewGuid().ToString("N");
        var quotedSchema = "\"" + schema + "\"";
        var createdSchema = false;

        using var connection = SqlIntegrationConnections.CreateConnection("Postgres");
        connection.Open();
        try
        {
            SqlIntegrationConnections.ExecuteSql(connection, "CREATE SCHEMA " + quotedSchema);
            createdSchema = true;

            SqlIntegrationConnections.ExecuteSql(connection, $"""
                CREATE TABLE {quotedSchema}."{parentTable}" (
                    "ParentId" integer NOT NULL PRIMARY KEY,
                    "Name" varchar(32)
                )
                """);
            SqlIntegrationConnections.ExecuteSql(connection, $"""
                CREATE TABLE {quotedSchema}."{childTable}" (
                    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "LegacyId" serial NOT NULL UNIQUE,
                    "ParentId" integer NOT NULL,
                    "Amount" numeric(10,2) NOT NULL,
                    CONSTRAINT "{constraint}" FOREIGN KEY ("ParentId")
                        REFERENCES {quotedSchema}."{parentTable}"("ParentId")
                )
                """);
            SqlIntegrationConnections.ExecuteSql(connection, $"CREATE VIEW {quotedSchema}.\"{view}\" AS SELECT \"Id\", \"ParentId\" FROM {quotedSchema}.\"{childTable}\"");

            var provider = new PostgresSchemaProvider();
            var fields = provider.GetFieldInfos(connection, schema, childTable).ToList();
            Assert.Equal(["Id", "LegacyId", "ParentId", "Amount"], fields.Select(x => x.FieldName));
            Assert.Contains(fields, x => x.FieldName == "Id" && x.IsIdentity);
            Assert.Contains(fields, x => x.FieldName == "LegacyId" && x.IsIdentity);
            Assert.Contains(fields, x => x.FieldName == "Amount" && x.DataType == "numeric" && x.Size == 10 && x.Scale == 2);

            var identities = provider.GetIdentityFields(connection, schema, childTable).ToList();
            Assert.Contains("Id", identities);
            Assert.Contains("LegacyId", identities);
            Assert.Equal(["Id"], provider.GetPrimaryKeyFields(connection, schema, childTable).ToList());

            var foreignKey = Assert.Single(provider.GetForeignKeys(connection, schema, childTable));
            Assert.Equal("ParentId", foreignKey.FKColumn);
            Assert.Equal(schema, foreignKey.PKSchema);
            Assert.Equal(parentTable, foreignKey.PKTable);
            Assert.Equal("ParentId", foreignKey.PKColumn);

            var objects = provider.GetTableNames(connection)
                .Where(x => x.Schema == schema && (x.Table == parentTable || x.Table == childTable || x.Table == view))
                .ToDictionary(x => x.Table);
            Assert.Equal(3, objects.Count);
            Assert.False(objects[parentTable].IsView);
            Assert.False(objects[childTable].IsView);
            Assert.True(objects[view].IsView);
        }
        finally
        {
            if (createdSchema)
                SqlIntegrationConnections.ExecuteSql(connection, "DROP SCHEMA " + quotedSchema + " CASCADE");
        }
    }
}
