// <auto-generated />

namespace Serenity.Demo.BasicSamples;

/// <summary>An attribute that sets the editor type to <c>Serenity.Demo.BasicSamples.FilteredLookupDetailEditor</c> and its options.</summary>
public partial class FilteredLookupDetailEditorAttribute : CustomEditorAttribute
{
    /// <summary>The editor type key.</summary>
    public const string Key = "Serenity.Demo.BasicSamples.FilteredLookupDetailEditor";

    /// <summary>Creates a new instance of the <c>FilteredLookupDetailEditorAttribute</c> class.</summary>
    public FilteredLookupDetailEditorAttribute()
        : base(Key)
    {
    }
}