// <auto-generated />

namespace Serenity.Demo.BasicSamples;

/// <summary>An attribute that sets the editor type to <c>Serenity.Demo.BasicSamples.ChangingLookupTextEditor</c> and its options.</summary>
public partial class ChangingLookupTextEditorAttribute : LookupEditorBaseAttribute
{
    /// <summary>The editor type key.</summary>
    public const string Key = "Serenity.Demo.BasicSamples.ChangingLookupTextEditor";

    /// <summary>Creates a new instance of the <c>ChangingLookupTextEditorAttribute</c> class.</summary>
    public ChangingLookupTextEditorAttribute()
        : base(Key)
    {
    }
}