// <auto-generated />

namespace Serenity.Demo.BasicSamples;

/// <summary>An attribute that sets the formatter type to <c>Serenity.Demo.BasicSamples.InlineImageFormatter</c> and its options.</summary>
public partial class InlineImageFormatterAttribute : CustomFormatterAttribute
{
    /// <summary>The formatter type key.</summary>
    public const string Key = "Serenity.Demo.BasicSamples.InlineImageFormatter";

    /// <summary>Creates a new instance of the <c>InlineImageFormatterAttribute</c> class.</summary>
    public InlineImageFormatterAttribute()
        : base(Key)
    {
    }

    /// <summary>Gets or sets the <c>fileProperty</c> option.</summary>
    public string FileProperty
    {
        get { return GetOption<string>("fileProperty"); }
        set { SetOption("fileProperty", value); }
    }

    /// <summary>Gets or sets the <c>thumb</c> option.</summary>
    public bool Thumb
    {
        get { return GetOption<bool>("thumb"); }
        set { SetOption("thumb", value); }
    }
}