// <auto-generated />

namespace Serenity.Demo.BasicSamples;

/// <summary>An attribute that sets the editor type to <c>Serenity.Demo.BasicSamples.ProduceSeafoodCategoryEditor</c> and its options.</summary>
public partial class ProduceSeafoodCategoryEditorAttribute : LookupEditorBaseAttribute
{
    /// <summary>The editor type key.</summary>
    public const string Key = "Serenity.Demo.BasicSamples.ProduceSeafoodCategoryEditor";

    /// <summary>Creates a new instance of the <c>ProduceSeafoodCategoryEditorAttribute</c> class.</summary>
    public ProduceSeafoodCategoryEditorAttribute()
        : base(Key)
    {
    }
}