// <auto-generated />

namespace Serenity.Demo.BasicSamples;

/// <summary>An attribute that sets the editor type to <c>Serenity.Demo.BasicSamples.HardcodedValuesEditor</c> and its options.</summary>
public partial class HardcodedValuesEditorAttribute : CustomEditorAttribute
{
    /// <summary>The editor type key.</summary>
    public const string Key = "Serenity.Demo.BasicSamples.HardcodedValuesEditor";

    /// <summary>Creates a new instance of the <c>HardcodedValuesEditorAttribute</c> class.</summary>
    public HardcodedValuesEditorAttribute()
        : base(Key)
    {
    }
}