// <auto-generated />

namespace Serenity.Demo.BasicSamples.MVC;

/// <summary>Provides paths to ECMAScript module entry points.</summary>
public static partial class ESM
{
    /// <summary>The module path for the <c>BasicSamplesLayout</c> entry point.</summary>
    public const string BasicSamplesLayout = "~/Serenity.Demo.BasicSamples/esm/Modules/BasicSamplesLayout.js";
    /// <summary>The module path for the <c>ChangingLookupTextPage</c> entry point.</summary>
    public const string ChangingLookupTextPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Editors/ChangingLookupText/ChangingLookupTextPage.js";
    /// <summary>The module path for the <c>ChartInDialogPage</c> entry point.</summary>
    public const string ChartInDialogPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Dialogs/ChartInDialog/ChartInDialogPage.js";
    /// <summary>The module path for the <c>CloneableEntityDialogPage</c> entry point.</summary>
    public const string CloneableEntityDialogPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Dialogs/CloneableEntityDialog/CloneableEntityDialogPage.js";
    /// <summary>The module path for the <c>CustomLinksInGridPage</c> entry point.</summary>
    public const string CustomLinksInGridPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Grids/CustomLinksInGrid/CustomLinksInGridPage.js";
    /// <summary>The module path for the <c>DefaultValuesInNewDialogPage</c> entry point.</summary>
    public const string DefaultValuesInNewDialogPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Dialogs/DefaultValuesInNewDialog/DefaultValuesInNewDialogPage.js";
    /// <summary>The module path for the <c>DialogBoxesPage</c> entry point.</summary>
    public const string DialogBoxesPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Dialogs/DialogBoxes/DialogBoxesPage.js";
    /// <summary>The module path for the <c>EnablingRowSelectionPage</c> entry point.</summary>
    public const string EnablingRowSelectionPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Grids/EnablingRowSelection/EnablingRowSelectionPage.js";
    /// <summary>The module path for the <c>EntityDialogAsPanelPage</c> entry point.</summary>
    public const string EntityDialogAsPanelPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Dialogs/EntityDialogAsPanel/EntityDialogAsPanelPage.js";
    /// <summary>The module path for the <c>FilteredLookupInDetailPage</c> entry point.</summary>
    public const string FilteredLookupInDetailPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Editors/FilteredLookupInDetail/FilteredLookupInDetailPage.js";
    /// <summary>The module path for the <c>GetInsertedRecordIdPage</c> entry point.</summary>
    public const string GetInsertedRecordIdPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Dialogs/GetInsertedRecordId/GetInsertedRecordIdPage.js";
    /// <summary>The module path for the <c>GridFilteredByCriteriaPage</c> entry point.</summary>
    public const string GridFilteredByCriteriaPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Grids/GridFilteredByCriteria/GridFilteredByCriteriaPage.js";
    /// <summary>The module path for the <c>GroupingAndSummariesInGridPage</c> entry point.</summary>
    public const string GroupingAndSummariesInGridPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Grids/GroupingAndSummariesInGrid/GroupingAndSummariesInGridPage.js";
    /// <summary>The module path for the <c>InitialValuesForQuickFiltersPage</c> entry point.</summary>
    public const string InitialValuesForQuickFiltersPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Grids/InitialValuesForQuickFilters/InitialValuesForQuickFiltersPage.js";
    /// <summary>The module path for the <c>InlineActionButtonsPage</c> entry point.</summary>
    public const string InlineActionButtonsPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Grids/InlineActionButtons/InlineActionButtonsPage.js";
    /// <summary>The module path for the <c>InlineImageInGridPage</c> entry point.</summary>
    public const string InlineImageInGridPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Grids/InlineImageInGrid/InlineImageInGridPage.js";
    /// <summary>The module path for the <c>LookupFilterByMultipleValuesPage</c> entry point.</summary>
    public const string LookupFilterByMultipleValuesPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Editors/LookupFilterByMultipleValues/LookupFilterByMultipleValuesPage.js";
    /// <summary>The module path for the <c>OtherFormInTabOneBarPage</c> entry point.</summary>
    public const string OtherFormInTabOneBarPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Dialogs/OtherFormInTabOneBar/OtherFormInTabOneBarPage.js";
    /// <summary>The module path for the <c>OtherFormInTabPage</c> entry point.</summary>
    public const string OtherFormInTabPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Dialogs/OtherFormInTab/OtherFormInTabPage.js";
    /// <summary>The module path for the <c>PopulateLinkedDataPage</c> entry point.</summary>
    public const string PopulateLinkedDataPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Dialogs/PopulateLinkedData/PopulateLinkedDataPage.js";
    /// <summary>The module path for the <c>ReadOnlyDialogPage</c> entry point.</summary>
    public const string ReadOnlyDialogPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Dialogs/ReadOnlyDialog/ReadOnlyDialogPage.js";
    /// <summary>The module path for the <c>RemovingAddButtonPage</c> entry point.</summary>
    public const string RemovingAddButtonPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Grids/RemovingAddButton/RemovingAddButtonPage.js";
    /// <summary>The module path for the <c>SelectWithHardcodedValuesPage</c> entry point.</summary>
    public const string SelectWithHardcodedValuesPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Editors/SelectWithHardcodedValues/SelectWithHardcodedValuesPage.js";
    /// <summary>The module path for the <c>SerialAutoNumberPage</c> entry point.</summary>
    public const string SerialAutoNumberPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Dialogs/SerialAutoNumber/SerialAutoNumberPage.js";
    /// <summary>The module path for the <c>StaticTextBlockPage</c> entry point.</summary>
    public const string StaticTextBlockPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Editors/StaticTextBlock/StaticTextBlockPage.js";
    /// <summary>The module path for the <c>ViewWithoutIDPage</c> entry point.</summary>
    public const string ViewWithoutIDPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Grids/ViewWithoutID/ViewWithoutIDPage.js";
    /// <summary>The module path for the <c>WrappedHeadersPage</c> entry point.</summary>
    public const string WrappedHeadersPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Grids/WrappedHeaders/WrappedHeadersPage.js";

    /// <summary>Provides module entry points in the <c>Modules</c> folder.</summary>
    public static partial class Modules
    {
        /// <summary>The module path for the <c>BasicSamplesLayout</c> entry point.</summary>
        public const string BasicSamplesLayout = "~/Serenity.Demo.BasicSamples/esm/Modules/BasicSamplesLayout.js";

        /// <summary>Provides module entry points in the <c>Modules/Dialogs</c> folder.</summary>
        public static partial class Dialogs
        {
            /// <summary>Provides module entry points in the <c>Modules/Dialogs/ChartInDialog</c> folder.</summary>
            public static partial class ChartInDialog
            {
                /// <summary>The module path for the <c>ChartInDialogPage</c> entry point.</summary>
                public const string ChartInDialogPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Dialogs/ChartInDialog/ChartInDialogPage.js";
            }

            /// <summary>Provides module entry points in the <c>Modules/Dialogs/CloneableEntityDialog</c> folder.</summary>
            public static partial class CloneableEntityDialog
            {
                /// <summary>The module path for the <c>CloneableEntityDialogPage</c> entry point.</summary>
                public const string CloneableEntityDialogPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Dialogs/CloneableEntityDialog/CloneableEntityDialogPage.js";
            }

            /// <summary>Provides module entry points in the <c>Modules/Dialogs/DefaultValuesInNewDialog</c> folder.</summary>
            public static partial class DefaultValuesInNewDialog
            {
                /// <summary>The module path for the <c>DefaultValuesInNewDialogPage</c> entry point.</summary>
                public const string DefaultValuesInNewDialogPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Dialogs/DefaultValuesInNewDialog/DefaultValuesInNewDialogPage.js";
            }

            /// <summary>Provides module entry points in the <c>Modules/Dialogs/DialogBoxes</c> folder.</summary>
            public static partial class DialogBoxes
            {
                /// <summary>The module path for the <c>DialogBoxesPage</c> entry point.</summary>
                public const string DialogBoxesPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Dialogs/DialogBoxes/DialogBoxesPage.js";
            }

            /// <summary>Provides module entry points in the <c>Modules/Dialogs/EntityDialogAsPanel</c> folder.</summary>
            public static partial class EntityDialogAsPanel
            {
                /// <summary>The module path for the <c>EntityDialogAsPanelPage</c> entry point.</summary>
                public const string EntityDialogAsPanelPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Dialogs/EntityDialogAsPanel/EntityDialogAsPanelPage.js";
            }

            /// <summary>Provides module entry points in the <c>Modules/Dialogs/GetInsertedRecordId</c> folder.</summary>
            public static partial class GetInsertedRecordId
            {
                /// <summary>The module path for the <c>GetInsertedRecordIdPage</c> entry point.</summary>
                public const string GetInsertedRecordIdPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Dialogs/GetInsertedRecordId/GetInsertedRecordIdPage.js";
            }

            /// <summary>Provides module entry points in the <c>Modules/Dialogs/OtherFormInTab</c> folder.</summary>
            public static partial class OtherFormInTab
            {
                /// <summary>The module path for the <c>OtherFormInTabPage</c> entry point.</summary>
                public const string OtherFormInTabPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Dialogs/OtherFormInTab/OtherFormInTabPage.js";
            }

            /// <summary>Provides module entry points in the <c>Modules/Dialogs/OtherFormInTabOneBar</c> folder.</summary>
            public static partial class OtherFormInTabOneBar
            {
                /// <summary>The module path for the <c>OtherFormInTabOneBarPage</c> entry point.</summary>
                public const string OtherFormInTabOneBarPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Dialogs/OtherFormInTabOneBar/OtherFormInTabOneBarPage.js";
            }

            /// <summary>Provides module entry points in the <c>Modules/Dialogs/PopulateLinkedData</c> folder.</summary>
            public static partial class PopulateLinkedData
            {
                /// <summary>The module path for the <c>PopulateLinkedDataPage</c> entry point.</summary>
                public const string PopulateLinkedDataPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Dialogs/PopulateLinkedData/PopulateLinkedDataPage.js";
            }

            /// <summary>Provides module entry points in the <c>Modules/Dialogs/ReadOnlyDialog</c> folder.</summary>
            public static partial class ReadOnlyDialog
            {
                /// <summary>The module path for the <c>ReadOnlyDialogPage</c> entry point.</summary>
                public const string ReadOnlyDialogPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Dialogs/ReadOnlyDialog/ReadOnlyDialogPage.js";
            }

            /// <summary>Provides module entry points in the <c>Modules/Dialogs/SerialAutoNumber</c> folder.</summary>
            public static partial class SerialAutoNumber
            {
                /// <summary>The module path for the <c>SerialAutoNumberPage</c> entry point.</summary>
                public const string SerialAutoNumberPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Dialogs/SerialAutoNumber/SerialAutoNumberPage.js";
            }
        }

        /// <summary>Provides module entry points in the <c>Modules/Editors</c> folder.</summary>
        public static partial class Editors
        {
            /// <summary>Provides module entry points in the <c>Modules/Editors/ChangingLookupText</c> folder.</summary>
            public static partial class ChangingLookupText
            {
                /// <summary>The module path for the <c>ChangingLookupTextPage</c> entry point.</summary>
                public const string ChangingLookupTextPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Editors/ChangingLookupText/ChangingLookupTextPage.js";
            }

            /// <summary>Provides module entry points in the <c>Modules/Editors/FilteredLookupInDetail</c> folder.</summary>
            public static partial class FilteredLookupInDetail
            {
                /// <summary>The module path for the <c>FilteredLookupInDetailPage</c> entry point.</summary>
                public const string FilteredLookupInDetailPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Editors/FilteredLookupInDetail/FilteredLookupInDetailPage.js";
            }

            /// <summary>Provides module entry points in the <c>Modules/Editors/LookupFilterByMultipleValues</c> folder.</summary>
            public static partial class LookupFilterByMultipleValues
            {
                /// <summary>The module path for the <c>LookupFilterByMultipleValuesPage</c> entry point.</summary>
                public const string LookupFilterByMultipleValuesPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Editors/LookupFilterByMultipleValues/LookupFilterByMultipleValuesPage.js";
            }

            /// <summary>Provides module entry points in the <c>Modules/Editors/SelectWithHardcodedValues</c> folder.</summary>
            public static partial class SelectWithHardcodedValues
            {
                /// <summary>The module path for the <c>SelectWithHardcodedValuesPage</c> entry point.</summary>
                public const string SelectWithHardcodedValuesPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Editors/SelectWithHardcodedValues/SelectWithHardcodedValuesPage.js";
            }

            /// <summary>Provides module entry points in the <c>Modules/Editors/StaticTextBlock</c> folder.</summary>
            public static partial class StaticTextBlock
            {
                /// <summary>The module path for the <c>StaticTextBlockPage</c> entry point.</summary>
                public const string StaticTextBlockPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Editors/StaticTextBlock/StaticTextBlockPage.js";
            }
        }

        /// <summary>Provides module entry points in the <c>Modules/Grids</c> folder.</summary>
        public static partial class Grids
        {
            /// <summary>Provides module entry points in the <c>Modules/Grids/CustomLinksInGrid</c> folder.</summary>
            public static partial class CustomLinksInGrid
            {
                /// <summary>The module path for the <c>CustomLinksInGridPage</c> entry point.</summary>
                public const string CustomLinksInGridPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Grids/CustomLinksInGrid/CustomLinksInGridPage.js";
            }

            /// <summary>Provides module entry points in the <c>Modules/Grids/EnablingRowSelection</c> folder.</summary>
            public static partial class EnablingRowSelection
            {
                /// <summary>The module path for the <c>EnablingRowSelectionPage</c> entry point.</summary>
                public const string EnablingRowSelectionPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Grids/EnablingRowSelection/EnablingRowSelectionPage.js";
            }

            /// <summary>Provides module entry points in the <c>Modules/Grids/GridFilteredByCriteria</c> folder.</summary>
            public static partial class GridFilteredByCriteria
            {
                /// <summary>The module path for the <c>GridFilteredByCriteriaPage</c> entry point.</summary>
                public const string GridFilteredByCriteriaPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Grids/GridFilteredByCriteria/GridFilteredByCriteriaPage.js";
            }

            /// <summary>Provides module entry points in the <c>Modules/Grids/GroupingAndSummariesInGrid</c> folder.</summary>
            public static partial class GroupingAndSummariesInGrid
            {
                /// <summary>The module path for the <c>GroupingAndSummariesInGridPage</c> entry point.</summary>
                public const string GroupingAndSummariesInGridPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Grids/GroupingAndSummariesInGrid/GroupingAndSummariesInGridPage.js";
            }

            /// <summary>Provides module entry points in the <c>Modules/Grids/InitialValuesForQuickFilters</c> folder.</summary>
            public static partial class InitialValuesForQuickFilters
            {
                /// <summary>The module path for the <c>InitialValuesForQuickFiltersPage</c> entry point.</summary>
                public const string InitialValuesForQuickFiltersPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Grids/InitialValuesForQuickFilters/InitialValuesForQuickFiltersPage.js";
            }

            /// <summary>Provides module entry points in the <c>Modules/Grids/InlineActionButtons</c> folder.</summary>
            public static partial class InlineActionButtons
            {
                /// <summary>The module path for the <c>InlineActionButtonsPage</c> entry point.</summary>
                public const string InlineActionButtonsPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Grids/InlineActionButtons/InlineActionButtonsPage.js";
            }

            /// <summary>Provides module entry points in the <c>Modules/Grids/InlineImageInGrid</c> folder.</summary>
            public static partial class InlineImageInGrid
            {
                /// <summary>The module path for the <c>InlineImageInGridPage</c> entry point.</summary>
                public const string InlineImageInGridPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Grids/InlineImageInGrid/InlineImageInGridPage.js";
            }

            /// <summary>Provides module entry points in the <c>Modules/Grids/RemovingAddButton</c> folder.</summary>
            public static partial class RemovingAddButton
            {
                /// <summary>The module path for the <c>RemovingAddButtonPage</c> entry point.</summary>
                public const string RemovingAddButtonPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Grids/RemovingAddButton/RemovingAddButtonPage.js";
            }

            /// <summary>Provides module entry points in the <c>Modules/Grids/ViewWithoutID</c> folder.</summary>
            public static partial class ViewWithoutID
            {
                /// <summary>The module path for the <c>ViewWithoutIDPage</c> entry point.</summary>
                public const string ViewWithoutIDPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Grids/ViewWithoutID/ViewWithoutIDPage.js";
            }

            /// <summary>Provides module entry points in the <c>Modules/Grids/WrappedHeaders</c> folder.</summary>
            public static partial class WrappedHeaders
            {
                /// <summary>The module path for the <c>WrappedHeadersPage</c> entry point.</summary>
                public const string WrappedHeadersPage = "~/Serenity.Demo.BasicSamples/esm/Modules/Grids/WrappedHeaders/WrappedHeadersPage.js";
            }
        }
    }
}