// <auto-generated />

namespace Serenity.Demo.BasicSamples.MVC;

/// <summary>Provides paths to view files.</summary>
public static partial class Views
{
    /// <summary>The path to the <c>BasicSamplesLayout</c> view.</summary>
    public const string BasicSamplesLayout = "~/Modules/BasicSamplesLayout.cshtml";
    /// <summary>Provides view paths in the <c>Dialogs</c> folder.</summary>
    public static partial class Dialogs
    {
        /// <summary>Provides view paths in the <c>Dialogs/OtherFormInTab</c> folder.</summary>
        public static partial class OtherFormInTab
        {
            /// <summary>The path to the <c>Index</c> view.</summary>
            public const string Index = "~/Areas/Serenity.Demo.BasicSamples/Dialogs/OtherFormInTab/Index.cshtml";
        }

        /// <summary>Provides view paths in the <c>Dialogs/OtherFormInTabOneBar</c> folder.</summary>
        public static partial class OtherFormInTabOneBar
        {
            /// <summary>The path to the <c>Index</c> view.</summary>
            public const string Index = "~/Areas/Serenity.Demo.BasicSamples/Dialogs/OtherFormInTabOneBar/Index.cshtml";
        }

        /// <summary>Provides view paths in the <c>Dialogs/PopulateLinkedData</c> folder.</summary>
        public static partial class PopulateLinkedData
        {
            /// <summary>The path to the <c>Index</c> view.</summary>
            public const string Index = "~/Areas/Serenity.Demo.BasicSamples/Dialogs/PopulateLinkedData/Index.cshtml";
        }

        /// <summary>Provides view paths in the <c>Dialogs/ReadOnlyDialog</c> folder.</summary>
        public static partial class ReadOnlyDialog
        {
            /// <summary>The path to the <c>Index</c> view.</summary>
            public const string Index = "~/Areas/Serenity.Demo.BasicSamples/Dialogs/ReadOnlyDialog/Index.cshtml";
        }

        /// <summary>Provides view paths in the <c>Dialogs/SerialAutoNumber</c> folder.</summary>
        public static partial class SerialAutoNumber
        {
            /// <summary>The path to the <c>Index</c> view.</summary>
            public const string Index = "~/Areas/Serenity.Demo.BasicSamples/Dialogs/SerialAutoNumber/Index.cshtml";
        }
    }

    /// <summary>Provides view paths in the <c>Editors</c> folder.</summary>
    public static partial class Editors
    {
        /// <summary>Provides view paths in the <c>Editors/ChangingLookupText</c> folder.</summary>
        public static partial class ChangingLookupText
        {
            /// <summary>The path to the <c>Index</c> view.</summary>
            public const string Index = "~/Areas/Serenity.Demo.BasicSamples/Editors/ChangingLookupText/Index.cshtml";
        }

        /// <summary>Provides view paths in the <c>Editors/FilteredLookupInDetail</c> folder.</summary>
        public static partial class FilteredLookupInDetail
        {
            /// <summary>The path to the <c>Index</c> view.</summary>
            public const string Index = "~/Areas/Serenity.Demo.BasicSamples/Editors/FilteredLookupInDetail/Index.cshtml";
        }

        /// <summary>Provides view paths in the <c>Editors/LookupFilterByMultipleValues</c> folder.</summary>
        public static partial class LookupFilterByMultipleValues
        {
            /// <summary>The path to the <c>Index</c> view.</summary>
            public const string Index = "~/Areas/Serenity.Demo.BasicSamples/Editors/LookupFilterByMultipleValues/Index.cshtml";
        }

        /// <summary>Provides view paths in the <c>Editors/SelectWithHardcodedValues</c> folder.</summary>
        public static partial class SelectWithHardcodedValues
        {
            /// <summary>The path to the <c>Index</c> view.</summary>
            public const string Index = "~/Areas/Serenity.Demo.BasicSamples/Editors/SelectWithHardcodedValues/Index.cshtml";
        }

        /// <summary>Provides view paths in the <c>Editors/StaticTextBlock</c> folder.</summary>
        public static partial class StaticTextBlock
        {
            /// <summary>The path to the <c>Index</c> view.</summary>
            public const string Index = "~/Areas/Serenity.Demo.BasicSamples/Editors/StaticTextBlock/Index.cshtml";
        }
    }

    /// <summary>Provides view paths in the <c>Grids</c> folder.</summary>
    public static partial class Grids
    {
        /// <summary>Provides view paths in the <c>Grids/CustomLinksInGrid</c> folder.</summary>
        public static partial class CustomLinksInGrid
        {
            /// <summary>The path to the <c>Index</c> view.</summary>
            public const string Index = "~/Areas/Serenity.Demo.BasicSamples/Grids/CustomLinksInGrid/Index.cshtml";
        }

        /// <summary>Provides view paths in the <c>Grids/EnablingRowSelection</c> folder.</summary>
        public static partial class EnablingRowSelection
        {
            /// <summary>The path to the <c>Index</c> view.</summary>
            public const string Index = "~/Areas/Serenity.Demo.BasicSamples/Grids/EnablingRowSelection/Index.cshtml";
        }

        /// <summary>Provides view paths in the <c>Grids/GridFilteredByCriteria</c> folder.</summary>
        public static partial class GridFilteredByCriteria
        {
            /// <summary>The path to the <c>Index</c> view.</summary>
            public const string Index = "~/Areas/Serenity.Demo.BasicSamples/Grids/GridFilteredByCriteria/Index.cshtml";
        }

        /// <summary>Provides view paths in the <c>Grids/GroupingAndSummariesInGrid</c> folder.</summary>
        public static partial class GroupingAndSummariesInGrid
        {
            /// <summary>The path to the <c>Index</c> view.</summary>
            public const string Index = "~/Areas/Serenity.Demo.BasicSamples/Grids/GroupingAndSummariesInGrid/Index.cshtml";
        }

        /// <summary>Provides view paths in the <c>Grids/InitialValuesForQuickFilters</c> folder.</summary>
        public static partial class InitialValuesForQuickFilters
        {
            /// <summary>The path to the <c>Index</c> view.</summary>
            public const string Index = "~/Areas/Serenity.Demo.BasicSamples/Grids/InitialValuesForQuickFilters/Index.cshtml";
        }

        /// <summary>Provides view paths in the <c>Grids/InlineActionButtons</c> folder.</summary>
        public static partial class InlineActionButtons
        {
            /// <summary>The path to the <c>Index</c> view.</summary>
            public const string Index = "~/Areas/Serenity.Demo.BasicSamples/Grids/InlineActionButtons/Index.cshtml";
        }

        /// <summary>Provides view paths in the <c>Grids/InlineImageInGrid</c> folder.</summary>
        public static partial class InlineImageInGrid
        {
            /// <summary>The path to the <c>Index</c> view.</summary>
            public const string Index = "~/Areas/Serenity.Demo.BasicSamples/Grids/InlineImageInGrid/Index.cshtml";
        }

        /// <summary>Provides view paths in the <c>Grids/RemovingAddButton</c> folder.</summary>
        public static partial class RemovingAddButton
        {
            /// <summary>The path to the <c>Index</c> view.</summary>
            public const string Index = "~/Areas/Serenity.Demo.BasicSamples/Grids/RemovingAddButton/Index.cshtml";
        }

        /// <summary>Provides view paths in the <c>Grids/ViewWithoutID</c> folder.</summary>
        public static partial class ViewWithoutID
        {
            /// <summary>The path to the <c>Index</c> view.</summary>
            public const string Index = "~/Areas/Serenity.Demo.BasicSamples/Grids/ViewWithoutID/Index.cshtml";
        }

        /// <summary>Provides view paths in the <c>Grids/WrappedHeaders</c> folder.</summary>
        public static partial class WrappedHeaders
        {
            /// <summary>The path to the <c>Index</c> view.</summary>
            public const string Index = "~/Areas/Serenity.Demo.BasicSamples/Grids/WrappedHeaders/Index.cshtml";
        }
    }
}