// <auto-generated />

namespace Serene.Administration;

/// <summary>An attribute that sets the editor type to <c>Serene.Administration.PermissionCheckEditor</c> and its options.</summary>
public partial class PermissionCheckEditorAttribute : CustomEditorAttribute
{
    /// <summary>The editor type key.</summary>
    public const string Key = "Serene.Administration.PermissionCheckEditor";

    /// <summary>Creates a new instance of the <c>PermissionCheckEditorAttribute</c> class.</summary>
    public PermissionCheckEditorAttribute()
        : base(Key)
    {
    }

    /// <summary>Gets or sets the <c>implicitPermissions</c> option.</summary>
    public object ImplicitPermissions
    {
        get { return GetOption<object>("implicitPermissions"); }
        set { SetOption("implicitPermissions", value); }
    }

    /// <summary>Gets or sets the <c>rolePermissions</c> option.</summary>
    public object RolePermissions
    {
        get { return GetOption<object>("rolePermissions"); }
        set { SetOption("rolePermissions", value); }
    }

    /// <summary>Gets or sets the <c>showRevoke</c> option.</summary>
    public bool ShowRevoke
    {
        get { return GetOption<bool>("showRevoke"); }
        set { SetOption("showRevoke", value); }
    }

    /// <summary>Gets or sets the <c>value</c> option.</summary>
    public object Value
    {
        get { return GetOption<object>("value"); }
        set { SetOption("value", value); }
    }
}