// <auto-generated />

namespace Serene.Administration;

/// <summary>An attribute that sets the editor type to <c>Serene.Administration.RoleCheckEditor</c> and its options.</summary>
public partial class RoleCheckEditorAttribute : CustomEditorAttribute
{
    /// <summary>The editor type key.</summary>
    public const string Key = "Serene.Administration.RoleCheckEditor";

    /// <summary>Creates a new instance of the <c>RoleCheckEditorAttribute</c> class.</summary>
    public RoleCheckEditorAttribute()
        : base(Key)
    {
    }
}