CREATE DATABASE [$$DbAlias$$]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'$$DbAlias$$', FILENAME = N'$$DbPath$$.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'$$DbAlias$$_log', FILENAME = N'$$DbPath$$.ldf' , SIZE = 4096KB, MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO
ALTER DATABASE [$$DbAlias$$] SET COMPATIBILITY_LEVEL = 90
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [$$DbAlias$$].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [$$DbAlias$$] SET ANSI_NULL_DEFAULT ON 
GO
ALTER DATABASE [$$DbAlias$$] SET ANSI_NULLS ON 
GO
ALTER DATABASE [$$DbAlias$$] SET ANSI_PADDING ON 
GO
ALTER DATABASE [$$DbAlias$$] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [$$DbAlias$$] SET ARITHABORT ON 
GO
ALTER DATABASE [$$DbAlias$$] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [$$DbAlias$$] SET AUTO_CREATE_STATISTICS OFF 
GO
ALTER DATABASE [$$DbAlias$$] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [$$DbAlias$$] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [$$DbAlias$$] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [$$DbAlias$$] SET CURSOR_DEFAULT  LOCAL 
GO
ALTER DATABASE [$$DbAlias$$] SET CONCAT_NULL_YIELDS_NULL ON 
GO
ALTER DATABASE [$$DbAlias$$] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [$$DbAlias$$] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [$$DbAlias$$] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [$$DbAlias$$] SET  DISABLE_BROKER 
GO
ALTER DATABASE [$$DbAlias$$] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [$$DbAlias$$] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [$$DbAlias$$] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [$$DbAlias$$] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [$$DbAlias$$] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [$$DbAlias$$] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [$$DbAlias$$] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [$$DbAlias$$] SET RECOVERY SIMPLE
GO
ALTER DATABASE [$$DbAlias$$] SET MULTI_USER 
GO
ALTER DATABASE [$$DbAlias$$] SET PAGE_VERIFY NONE  
GO
ALTER DATABASE [$$DbAlias$$] SET DB_CHAINING OFF 
GO
ALTER DATABASE [$$DbAlias$$] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [$$DbAlias$$] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
EXEC sys.sp_db_vardecimal_storage_format N'$$DbAlias$$', N'ON'
GO
