<Project Sdk="Microsoft.NET.Sdk.Razor">
  <ItemGroup>
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="FastMember" />
    <PackageReference Include="FluentMigrator" />
    <PackageReference Include="FluentMigrator.Extensions.SqlServer" />
    <PackageReference Include="FluentMigrator.Extensions.Postgres" />
    <PackageReference Include="MailKit" />
    <PackageReference Include="nClam" />
    <ProjectReference Include="$(SerenitySrc)..\packages\corelib\Serenity.Corelib.csproj" Condition="Exists('$(SerenitySrc)..\packages\corelib\Serenity.Corelib.csproj') and '$(AddAutoRefs)' == 'true'"
      Private="false" ReferenceOutputAssembly="false" SkipGetTargetFrameworkProperties="true" UndefineProperties="TargetFramework" 
      ExcludeAssets="all" PrivateAssets="all" DisableTransitiveProjectReferences="true" DisableTransitiveFrameworkReferences="true" />
  </ItemGroup>
</Project>